### ISSUE TITLE
Installing mosh without sudo access

### ISSUE THREAD

**Issue by xapple** [mobile-shell/mosh#1007]
I'm not a sudoer on the server I want to access. How can I install mosh onto it? This is the script I have come up with, but it doesn't work.

    # libtool
    mkdir -p ~/programs/libtool
    mkdir ~/test
    cd ~/test
    wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
    tar xf libtool-2.4.6.tar.gz
    cd libtool-*
    ./configure --prefix=$HOME/programs/libtool
    make
    make install

    # protobuf, the Protocol Buffers from google
    mkdir -p ~/programs/protobuf
    cd ~/test
    wget https://github.com/protocolbuffers/protobuf/archive/v3.6.1.tar.gz
    tar xf protobuf-*.tar.gz
    cd protobuf-*
    ./autogen.sh
    ./configure --prefix=$HOME/programs/protobuf
    make
    make install

    # Export variables #
    export PATH="$PATH:$HOME/programs/protobuf/bin"
    export PKG_CONFIG_PATH=$HOME/programs/protobuf/lib/pkgconfig

    # mosh, mobile-shell
    mkdir -p ~/programs/mosh
    cd ~/test
    wget https://mosh.org/mosh-1.3.2.tar.gz
    tar xf mosh-*.gz
    cd mosh-*
    ./configure --prefix=$HOME/programs/mosh CFLAGS="-I$HOME/programs/protobuf/include/google/protobuf" LDFLAGS="-L$HOME/programs/protobuf/lib"
    make
    make install

It fails at the `./autogen.sh` part with the following error.

    + mkdir -p third_party/googletest/m4
    + autoreconf -f -i -Wall,no-obsolete
    configure.ac:104: error: possibly undefined macro: AC_PROG_LIBTOOL
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by keithw** [comment]
It looks like your difficulty is in installing protobuf -- the question is probably better directed at them. But please note that you probably want to be installing protobuf from a release, not from the development tree. If you do that you don't have to run autogen.sh and you don't need autotools or libtool to be installed (these tools are generally only needed by developers). Good luck!

**Comment by xapple** [comment]
The only reason I am doing all this is to access your product, so I fell like directing the question to you is appropriate. I don't have any direct interest in any of these other packages.

I'm not sure why you are suggesting that I am installing protobuf from the development tree? I am installing protobuf from a release. You can see that in the download URL, it's the latest release as listed in the "releases" section on GitHub.

You also suggest that I don't need `libtool` in such a case. How is that so? The error message received `possibly undefined macro: AC_PROG_LIBTOOL` specifically indicates that I can't compile without it.

**Comment by keithw** [comment]
I want to make sure we're clear: Mosh is not a product. It's a piece of free software, that you are downloading and using without charge, and we do this on a volunteer basis. We're happy to help educate you on how to build Mosh from source, but you'll have to do your part too. Otherwise you should be asking these questions of your system administrator or paying somebody to help you with this.

The URL you provided (https://github.com/protocolbuffers/protobuf/archive/v3.6.1.tar.gz) is not a protobuf release; it's a GitHub snapshot of the development tree. It hasn't been "released", which is to say, it doesn't have a ./configure in the archive and requires developer tools (e.g. autotools and libtool) to build. GitHub has these for every tag (I think actually for every commit!); it doesn't mean it's a release archive.

The release is here: https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz This includes a ./configure so you don't need the developer tools (like libtool or autotools).

It looks like Google also makes binary builds of protobuf available so you don't even have to compile it: https://github.com/protocolbuffers/protobuf/releases

You could also compile mosh-server statically somewhere else and just copy it to the machine in question.

**Comment by xapple** [comment]
Ah thanks for that, by using the CPP version of `protobuf` I was able to get further.

That's definitely a piece of information that would go well in the https://github.com/mobile-shell/mosh/wiki/Build-Instructions document (that currently assumes the user is necessarily amongst the list of sudoers on both machines and thus doesn't day much about the dependencies).

Now the problem is that when I run `./configure` in the `mosh` directory I get `configure: error: OpenSSL crypto library not found`.

I really think you should revise your distribution/install strategy for mosh. The use case where you don't own the remote server is a common one!

**Comment by xapple** [comment]
OK so I installed OpenSSL from source. This is my install script now:  https://gist.github.com/xapple/9c50d7767b3cd8d1f7ba75e2f97c8da2
But it fails on the `make` step inside the `mosh` directory with this output:  https://gist.github.com/xapple/9db34e4642af67c931ba42359e7a02f6

`mosh` is currently uninstallable in it's current distribution strategy.

**Comment by keithw** [comment]
I think you're running into a recent protobuf change to require a C++11 compiler, and you're using a compiler that doesn't default to C++11. (Mosh in Git has a workaround for this but the protobuf change happened after our most recent release.)

Try configuring Mosh with ./configure CXXFLAGS="-std=c++11 -g -O2".

Or if your compiler really isn't capable of C++11, you'll need an earlier release of protobuf. (Even version 2 will work fine.)

**Comment by xapple** [comment]
Ah thanks that last complier flag made it work.

For anyone coming here later, now I have to invoke mosh like this:

     mosh --server='env LD_LIBRARY_PATH=/home/xapple/programs/protobuf/lib:/home/xapple/programs/openssl/lib /home/lucas/programs/mosh/bin/mosh-server' ssh.cluster.com

Hard to estimate how much of mosh's potential user base owns the remote server and how much doesn't. But you certainly are cutting down your user base drastically, by denying access to those that don't own the remote machine (because I don't know many people who are ready to go through all this just to get it installed).

**Comment by eminence** [comment]
Nearly every bit of of open-source software suffers from the problem you just described (how to get it installed).  Some software is even harder than mosh, because it requires root! (mosh doesn't require root to install or run).  Some software is easier because it is so popular that it's almost always installed by default.

I understand that compiling software from source can be difficult at times, but hopefully you learned something useful from this exercise :smiley:.  Also, we welcome any improvements to the "Build Instructions" wiki -- anyone with a github account is free to edit it.

**Comment by ssb22** [comment]
[https://gist.github.com/eminence/85961d47244a140fde89314837d0db0a](The gist mentioned on the Build Instructions wiki) worked for me on an Ubuntu 18.04 server on which I have no root access.  I only had to change its `INSTALL_DIR` setting.  Its builds of `ncursesw` and `ncurses` failed, but that didn't matter on this particular machine because it already had ncurses libraries installed system-wide.  I ended up with things being installed under the `mosh` subdirectory of my home directory (as that's what I'd edited `INSTALL_DIR` to), and then on my own machine I can do `mosh --server=mosh/bin/mosh-server ds` and I'm in.  (My `.ssh/config` is set to recognise `ds` as the name of the server.)
