### ISSUE TITLE
mosh client hangs if command exits during network outage

### ISSUE THREAD

**Issue by andres-erbsen** [mobile-shell/mosh#1011]
mosh client hangs if the remote commands exits during network outage. This happens when running a long-lived job over mosh as (`mosh $target -- dothings`), and that job exits with an error. A workaround is to open a shell using mosh and manually call the job from that shell, and manually close the shell once the job is done.

How to reproduce:

1. `mosh $target -- sleep 10`
2. disconnect from the network
3. wait 10 seconds
4. reconnect to the network
5. observe that this mosh session does not reconnect, and `mosh-server` has already exited on the server side.

I think it would be less surprising to have `mosh-server` stick around (even after `sleep` as exited) until the client reconnects and tells it to shut down (or until `MOSH_SERVER_NETWORK_TMOUT`).

**Comment by achernya** [comment]
I think this is unfortunately working-as-implemented. There's an explicit clause for mosh-server to timeout waiting for a client acknowledgement in https://github.com/mobile-shell/mosh/blob/master/src/frontend/mosh-server.cc#L880-L888 -- https://github.com/mobile-shell/mosh/blob/03087e7a761df300c2d8cd6e072890f8e1059dfa/src/network/transportsender-impl.h#L384 does retry for a bit, but I'm not sure what units ACTIVE_RETRY_TIMEOUT is in. I think it's milliseconds, because that's what https://github.com/mobile-shell/mosh/blob/311764712e183b272cd4529eec424ff7b33998de/src/util/timestamp.cc#L65 is in. Either way, we'll retry for 10ms a few times after the timeout. 

It's not obvious to me that having a mosh-server stick around after its child process has exited just for an acknowledgement is a good idea. What happens if the mosh-client has since been killed? We already have lots of people complaining about stale mosh-server processes, and this seems like it would be likely to make it worse. So I am closing this as not planned for now
