### ISSUE TITLE
Mosh on system with closed UDP ports

### ISSUE THREAD

**Issue by Miro-Astore** [mobile-shell/mosh#1070]
Hi, I would like to use mosh on a HPC that my university runs which naturally has firewalls and the like. I've managed to compile it locally without root and I can start a mosh session out to my own systems running mosh but I can't mosh in. I get 

mosh: Nothing received from server on UDP port 60001. [To quit: Ctrl-^ .]                                                      

Any ideas if I should pursue port tunneling or something along those lines? Not very experienced in this.

Thank you.

**Comment by eminence** [comment]
It's hard for us to give specific advice, because we're not familiar with the specific configuration of your HPC system.   Your best bet would probably be to talk to the team that manages your HPC system to see if they can help.   If there are specific questions about how mosh works, we can help with that (but the mosh.org website does a good job describing this)

**Comment by Miro-Astore** [comment]
Thanks, I asked specificially if there were any open UDP ports and they said no. I don't think they're going to support me trying mosh so I'm sort of on my own. If you have any general directions I could try that would be helpful but this is borne out of curiosity and a desire to learn more about networking more than anything else so I would not ask you to waste too much of your time.

**Comment by normanr** [comment]
You could try sshuttle (or socat?) to get the udp packets into the HPC.

But why don't you just use mosh to a host that's close to the HPC, and then ssh from that host to the HPC?

**Comment by Miro-Astore** [comment]
You know what, I really should have thought of that second option. Thank
you very much.

I'll try the other options for study but yeah I can definitely do the
second one.

Best, Miro

**Comment by tux2bsd** [comment]
The problem is primarily the message.
`mosh: Nothing received from server on UDP port 60002. [To quit: Ctrl-^ .]`
That is not a problem, I have not allowed it through the firewall.
The message and behaviour needs altering.  The message (above) indicates the program should do something when it doesn't.
What should happen:
`mosh: No data from server on UDP port 60002. [Any key quits. Or, wait.]`
and it should also automatically close, as it does. 

I'm just giving it a quick try from ubuntu 20.04 so my "mosh" is well out of date.  But this bug isn't closed.

**Comment by tux2bsd** [comment]
an additions note of no relation to this bug:
`Ctrl-^`
Stupid key combinations like that help no one.

**Comment by tux2bsd** [comment]
@achernya you should vet your issues backlog more often.
