### ISSUE TITLE
mosh prevents the use of mouse wheel in emacs, nano, less, vi etc.

### ISSUE THREAD

**Issue by avatar-lavventura** [mobile-shell/mosh#1110]
I want to use `mouse-wheel` in `emacs`, `nano`, `vim` etc. and also scrollback in the terminal history, which `ssh` does it.

When I do `mosh --no-init` I can scrollback in the terminal history but I cannot use mouse wheel in the `emacs`. Instead if I do only `mosh` without `--no-init` flag I can use mouse-scroll in emacs but cannot scroll back in the terminal history. I get lost how can I fix this.

In `mosh` is it possible to scrollback in the terminal history along with using mouse wheel in `emacs`, `nano`, `less`? 

https://github.com/mobile-shell/mosh/issues/122#issuecomment-623792008

> The root cause of not able to scroll is caused by `mosh` entering a
> "alternative screen" mode. It can be disabled using the --no-init flag
> ([see the doc][1]). Just `alias mosh='mosh --no-init'` and the problem
> will go away.

Please also see related comment for this issue: https://github.com/mobile-shell/mosh/issues/122#issuecomment-681952476

**Comment by andersk** [comment]
We’re sorry you’ve been misled by an incorrect comment.

`--no-init` is a kludge that prevents the terminal from disabling the local scrollbar, but it makes no promises about the resulting scrollback being useful. If you look carefully, you’ll find that it’s missing lots of lines, because Mosh typically optimizes screen updates by replacing existing lines instead of appending new ones.

Adding useful scrollback to Mosh is a difficult open issue (#122). On the other hand, passing mouse wheel events to applications with `--no-init` is literally *impossible*, as `--no-init` forces the outer terminal to be left in a mode where mouse wheel events are not transmitted to Mosh in the first place.

The behavior of `--no-init` is what it is. We don’t recommend it and we have no way to improve it. It only exists because otherwise some users would complain that we “took away their scrollbar”.

The mouse wheel works as expected in the programs you mentioned when using Mosh in the default mode. If you need scrollback in the terminal history, at this time, we recommend using `screen` or `tmux`, as has been discussed repeatedly in previous issues.

**Comment by avatar-lavventura** [comment]
@andersk  When I use `tmux` yes scrollback in the terminal history works, but than the mouse wheel does not work in the `emacs` or other mentioned programs. 

I have added `set -g mode-mouse on` into `.tmux.conf` , which did not helped or answer from (https://unix.stackexchange.com/a/161906/198423) as well. If there is another solution please guide me for it.

**Comment by andersk** [comment]
You need `set -g mouse on` in `.tmux.conf` (not `mouse-mode`).

**Comment by avatar-lavventura** [comment]
On my client `.tmux.conf` file I have `set -g mouse on`. Than I run `tmux` and scroll works fine. Afterwards when I do `mosh user@IP` scoll does not go back in the terminal history instead travels around the previously entered commads.

**Comment by avatar-lavventura** [comment]
I give up , I will just continue to use `ssh`. I still have doubt where `tmux` with `mosh` let users scroll back in terminal history and enables users to scroll using mouse wheel within `emacs, less, nano, more` etc.

**Comment by andersk** [comment]
You're welcome to use what works best for you, but if you'd like to debug this: do you have a `.tmux.conf` on the server (since that's where your `tmux` would be running)? Does it work with `tmux` inside `ssh`?

**Comment by avatar-lavventura** [comment]
On the server side I have `.tmux.conf` file that only has `set -g mouse on`. P

```
client $ mosh user@IP
remote $ tmux
```

I experince scroll back in the terminal history works, but it prevents me to copy some text from previois terminal history, it jumps back to current cursor spot right away. Also scroll does not work within `emacs, less` etc.
