### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by kamushadenes** [mobile-shell/mosh#1132]
Seems to be a recurrent subject, but given the number of issues and PRs, and the last commit date, it seems the project development is gone.

Are there any known alternatives?

**Comment by keithw** [comment]
No, the project has not been abandoned, but certainly our release cadence has slowed. We will need to do a release sometime this year that works around MacOS clock bugs and includes truecolor support. But I don't think we feel an urgent need, and COVID has interfered with our maintainer availability. We are proud of our perfect security track record and don't really want to rush anything -- clearly we are doing something right.

Please post this issue on the repository for TeX instead.

**Comment by nyuszika7h** [comment]
> COVID has interfered with our maintainer availability

I can understand that. But then again, COVID wasn't a thing from mid-2017 to late 2019 and there were still no releases. Personally I don't mind building mosh from source, but it would still be nice to have newer versions packaged. Sadly Debian/Ubuntu (and possibly other distributions) haven't backported true color support because there's been no new release.
