### ISSUE TITLE
pass-through of custom escape sequences

### ISSUE THREAD

**Issue by wilhelmy** [mobile-shell/mosh#1135]
Several terminal emulators support escape sequences that can either be bound to custom actions (such as urxvt) or that have a pre-defined meaning (such as sending notifications). It would be nice if mosh would allow the pass-through of these escape sequences: https://blog.vucica.net/2017/07/what-are-osc-terminal-control-sequences-escape-codes.html

**Comment by keithw** [comment]
Thanks for this! The challenge is that mosh-server can't simply "pass through" an escape sequence -- it needs to know how the sequence affects the persistent state of the terminal, because the sequences might come in when the mosh-client is off the network (or connected but with a very low frame rate). The mosh-server needs to know how to bring the mosh-client's state up-to-date when it returns.

Mosh does support and interpret some of those OSC escapes you linked; we're notionally happy to do more if a Pull Request is filed describing how they affect the persistent state of the terminal.

**Comment by wilhelmy** [comment]
I'm personally most interested in the ephemeral ones that don't modify terminal state at all, such as notifications :)
I don't think mosh should keep track of those.

**Comment by keithw** [comment]
Mosh **only** passes on changes to the terminal state -- that's how Mosh can take a stream of escape sequences coming in at 1 Gbps and turn it into a sequence of updates at 5 frames per second, allowing a slow client to keep up. Check out our implementation of the terminal bell or some of the OSC escapes you mentioned...

**Comment by rrrrrrrrrricoxi** [comment]
Related workaround for the file-transfer subset of this: since in-band escape sequences can't survive mosh's state sync, I went out-of-band — **[moshdrop](https://github.com/rrrrrrrrrricoxi/moshdrop)** (MIT) is a local pty wrapper that detects a file dragged into the terminal, uploads it over a parallel ssh channel, and pastes the remote path into your session. No mosh patching, nothing installed on the remote, byte-for-byte passthrough otherwise. macOS-only for now. Demo GIF in the README.
