### ISSUE TITLE
Tried to use mosh - and gave up

### ISSUE THREAD

**Issue by mooperd** [mobile-shell/mosh#1137]
Hey mosh people,

I just spend 1/2 hour trying to use mosh. I am on OSX trying to connect to ubuntu boxes. Got weird locale errors that did not google well. Gave up.

My 2¢ - I have about 15 years of linux experience and am not afraid to get my hands dirty but mosh has significant obscure barriers to entry. If you want to be a serious contender for the SSH crown then you'd better "just work" out of the box. No one in their right mind wants to deal with locale settings.

```
The locale requested by LC_CTYPE=C.UTF-8 isn't available here.
Running `locale-gen C.UTF-8' may be necessary.

mosh-client needs a UTF-8 native locale to run.

Unfortunately, the client's environment (LC_CTYPE=C.UTF-8) specifies
the character set "US-ASCII".
```

Ta,

Andrew

**Comment by damnskippy** [comment]
There is no alternative to mosh that has all the features that mosh has and is also actively maintained.

**Comment by keithw** [comment]
Sorry to hear of your troubles. The problem here is unrelated to Mosh -- you are trying to connect from a system that defaults to "C.UTF-8" to a system that doesn't know what that means. (The most recent versions of Debian and Ubuntu do have "C.UTF-8", but not older ones.) You will have similar problems with SSH, although SSH is less strict and will let you connect anyway, instead of bombing out with an error. Please search the GitHub issues for similar issues (e.g.  #1136).

For the time being, your best bet is probably something like:
- Upgrade the server to a more recent version of Ubuntu that has "C.UTF-8"
- Set your client-side LANG environment variable to something like "en_US.UTF-8" that is available on the server

Mosh is actively maintained, but sort of how TeX is. If we ever had a security hole, we would fix it!

**Comment by mooperd** [comment]
Would be nice if it produced a quietable warning rather than just failing with an obscure error. It's extremely rare that I have ever seen locale problems with ssh and I'm connecting to a large array of weird and wonderful devices.

**Comment by andersk** [comment]
FYI, Ubuntu has supported the `C.UTF-8` locale without any configuration or extra packages since Ubuntu 11.04, released ten years ago. All older Ubuntu releases have been [unsupported](https://wiki.ubuntu.com/Releases) for the last six years. It’s not unreasonable to expect that you’ll need to upgrade if you want to run modern software or if you want to remain secure.

Unlike SSH which just passes raw data between terminals, Mosh needs to interpret the data passing through it as UTF-8 in order to function correctly. This requires a working locale configuration.

**Comment by mooperd** [comment]
I'm connecting to an 18.04 ubuntu.

**Comment by andersk** [comment]
Ah, from a closer look, your error is coming from the client side, not the server side. macOS does not support `C.UTF-8`, so it’s unclear why that’s in your configuration at all, unless you tried to put it there manually in response to a similar error.

You should use a UTF-8 locale supported by your Mac. My Mac defaults to `LANG=en_US.UTF-8`, which is fine. Run `locale -a` for a list and `locale` to verify your current setting.

If you need to add additional locales to your Ubuntu server, you can install the `locales` package (should be installed already) and run `dpkg-reconfigure locales` to select them, or install the `locales-all` package.
