### ISSUE TITLE
Is it possible to set long heartbeats pocket interval when there is no input for a long time.

### ISSUE THREAD

**Issue by lunarjoll** [mobile-shell/mosh#1141]
I think it is lost battery in mobile phones.

**Comment by keithw** [comment]
Good question! The mosh-server does disable heartbeat packets when it hasn't received anything from the client in more than a minute (e.g. if the client goes offline or is suspended).

The mosh-client disables heartbeat packets if you suspend it (e.g. by typing `Ctrl-^ Ctrl-Z`, or by sending SIGSTOP). (If you're running an Android or iOS application that includes mosh-client, you may have to check with the app vendor to see how to suspend it.)

We don't disable heartbeats just because of a lack of input -- we do want the client (if running) to always truthfully disclose if it is showing a current vs. an out-of-date version of the terminal screen state.
