### ISSUE TITLE
Mosh clears the terminal and adds an empty lines on login

### ISSUE THREAD

**Issue by souew** [mobile-shell/mosh#1142]
server: Debian 10, mosh 1.3.2 [build mosh 1.3.2]
"ssh server" gives me this output:
```
[user@desktop ~]$ ssh server
user@server:~$
```
"mosh server" completely clears the screen and adds three additional empty lines:
```
  
  
user@server:~$
```

I don't mind clearing the screen, but I would like to get rid of the empty lines.

sshd_config:
  Port *redacted*
  PermitRootLogin no
  PubkeyAuthentication yes
  PasswordAuthentication no
  PermitEmptyPasswords no
  ChallengeResponseAuthentication no
  UsePAM no
  PrintMotd no
  PrintLastLog no

file /etc/motd
/etc/motd: empty

server:
echo $TERM
rxvt-unicode-256color

client:
echo $TERM
rxvt-unicode-256color

terminal used: rxvt-unicode with 256 color patch applied

other terminal tested - xterm, same behaviour

**Comment by souew** [comment]
After deleting /etc/motd,
and commenting out anything motd in  /etc/pam.d/login and /etc/pam.d/sshd I'm down to a single empty line.

**Comment by souew** [comment]
Tested in Alacritty with or without export TERM=xterm-256color, same thing.
So a single blank like after motd is an expected behavior? But what if I don't have a motd message, can I get rid of the blank line as well?

**Comment by achernya** [comment]
The "clears the screen" behavior is expected, as mosh emulates an entire terminal (like screen or tmux). Normally, the motd is printed by login(1) over a getty, but ssh and mosh have their own motd printing code. ssh does this at https://github.com/openssh/openssh-portable/blob/2d1ff2b9431393ad99ef496d5e3b9dd0d4f5ac8c/session.c#L791, which happens after any messages that PAM generates. mosh does this at https://github.com/mobile-shell/mosh/blob/cd7050613c13dc2989e22e6056378319b6abc66d/src/frontend/mosh-server.cc#L575, but with some hacks that are aware of what PAM would have done. This results in the following behaviors on my machine

mosh:
```
Linux HOSTNAME 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

achernya@HOSTNAME:~$
```

ssh:
```
Linux HOSTNAME 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Sun Jan 22 13:58:42 2023 from REDACTED
achernya@HOSTNAME:~$ 
```

The "Last login:" line is generated by ssh, and the "You have new mail" line generated by PAM. 

mosh, of course, doesn't use pam, so those two lines missing is expected. This brings us to the question of where are the newlines coming from? My suspicion is one of them is being generated by your dotfiles. As an experiment, I did `touch ~/.hushlogin`, and I do see that my mosh prompt is down 1 line from where I expect it to be, even if I run `mosh --no-init.` So that explains 1 empty line, it seems to be mosh's fault. I haven't tracked down where, as it seems it's not the motd-printing code. But the other line is probably coming from outside of mosh.

I've also verified that the first line is not coming from dotfiles by writing a simple shell script

```
#!/bin/sh
echo "This is the first line"
sleep 10
```

And we can see that the "first" line is actually on the second line. 

My best guess, which I haven't fully validated, is that this is because of https://github.com/mobile-shell/mosh/blob/cd7050613c13dc2989e22e6056378319b6abc66d/src/frontend/mosh-server.cc#L824 -- this \n will be written to a PTY, and should show up on the child shell.
