### ISSUE TITLE
Terminal Tab Title Issue

### ISSUE THREAD

**Issue by daron4ever** [mobile-shell/mosh#1264]
Hi,

I use mosh with iterm2 and changed the terminal tab title via js.

When I used mosh the first time, it changed all custom titles to:
`[mosh] my_custom_title (mosh-client)`

So I removed the mosh title by using `MOSH_TITLE_NOPREFIX`.

After that, I don't see my custom_title and I only can see "mosh client" on the terminal tab title.
The title is important to me to distinguish which tab I used for and I have many tabs in a terminal and a pretty narrow size of tab. 
I don't know how I only can see my custom titles with mosh.

Please help!

**Comment by achernya** [comment]
The behavior you're observing isn't really possible, as setting the environment variable literally just prevents the prefix from being printed per https://github.com/mobile-shell/mosh/blob/03087e7a761df300c2d8cd6e072890f8e1059dfa/src/frontend/stmclient.cc#L124-L127

So that sounds to me like an issue with how you're setting your custom title or iTerm2

**Comment by daron4ever** [comment]
> The behavior you're observing isn't really possible to be caused by mosh alone, as setting the environment variable literally just prevents the prefix from being printed per
> 
> https://github.com/mobile-shell/mosh/blob/03087e7a761df300c2d8cd6e072890f8e1059dfa/src/frontend/stmclient.cc#L124-L127
> 
> So that sounds to me like an issue with how you're setting your custom title or iTerm2

Thanks, but
For now, I just want to back to the status where MOSH_TITLE_NOPREFIX is not being used.
So I removed MOSH_TITLE_NOPREFIX when I run ssh, however, it still acts like I have MOSH_TITLE_NOPREFIX.
I reinstalled mosh on both the server and client side, but it didn't change at all.
