### ISSUE TITLE
ctrl-^ escape not ideal

### ISSUE THREAD

**Issue by pimlott** [mobile-shell/mosh#215]
This is issue 187 reformulated as a feature request.  There are two problems with the current escape mechanism:
- ctrl-^ is a commonly-used command in vi.
- Sending a literal ctrl-^ is awkward.

I would suggest using the same escape mechanism as ssh (newline tilde).  It has the following good properties:
- It is already familiar to users.
- The begin-escape sequence is two characters, thus rarely entered unintentionally.
- The first character (newline) of the escape gets sent immediately, so the user rarely sees his input swallowed.  (The necessity of sending a newline when you want the escape sequence is practically never an issue.)
- In the rare case that you enter the begin-escape sequence unintentionally, you just hint tilde again to send a literal tilde.  If the user is confused because his tilde didn't work, he is likely to do that anyway.

If you are wedded to preserving ctrl-^ . as the quit sequence, I would suggest at least making the behavior a little saner:
- ctrl-^ ctrl-^ should send a literal ctrl-^ (not two).
- ctrl-^ <char> should send literal ctrl-^ <char>, except for a fixed set of <char>s.  They may as well follow ssh, and you may as well reserve them now even if they are not implemented.

Making the escape key configurable may be considered.

**Comment by deadalnix** [comment]
Hi all,

I have 2 temrinal locked and telling me i can exit by using ctrl - ^ . I'm not sure what i'm supposed to do, but pressing the control key and the "^" key at the same sure doesn't work.

@keithw I see you made this configurable, however I've been unable to find anyway to configure it - the man pages for instance say nothing. All google search on the subject bring me to that bug report so that's not helpful.

**Comment by eminence** [comment]
It's in the man page for `mosh` : https://github.com/mobile-shell/mosh/blob/master/man/mosh.1#L289-L294

**Comment by cgull** [comment]
* If you're not using an English keyboard layout, it is sometimes difficult or impossible to generate the initial escape character, and you may have to change it as documented in `mosh.1`.  Try `Ctrl-6`, though, that may work.  It's hard to change this default now because it's so important, though.
* The full escape sequence is actually `Ctrl-^` then `.`, are you aware of that?  When viewed in our documentation, that `.` unfortunately can be misinterpreted as normal end-of-sentence punctuation or a typo.

**Comment by deadalnix** [comment]
Got it foreign keyboard, ^ is a dead key and it looks like it isn't working.

**Comment by langbeck** [comment]
@cgull `Ctrl-6` + `.` works for me, but `Ctrl-^` + `.` doesn't.
My keyboard layout is: http://s2.glbimg.com/hlQMZ_E87B3DB_96rVuO_pY2Yy8=/695x0/s.glbimg.com/po/tt2/f/original/2016/06/21/900px-kb_portuguese_brazilsvg_.png

**Comment by yangm97** [comment]
I'm using US-International and `Ctrl-6` results in a "boop" from macOS. Not sure why.

**Comment by nextgenthemes** [comment]
As a German on German keyboard I had no clue how to read it and what to press. `CTRL (STRG) + 6 + .` however worked after reading it here.

Considering that mosh reminded me to install some language pack on the server I was moshing into there could be a better clue for international users. On German keyboard the `^` sign is actually typed by with they key left of `1`.

Where is it on US Keyboard? I first thought it meant pressing shift.

**Comment by kwinz** [comment]
I use the US-int keyboard layout.
No combination of CTRL+(shift)6 and . has done anything for me.
I am usually not an idiot, but I can't quit mosh sessions.
I have to kill the mosh client from a separate shell.
If I can't do it - loads of people can't do it. I go as far as to say the current default behavior is stupid.

**Comment by bvdlingen** [comment]
Dutch using the US-int keyboard layout.
 CTRL - (shift) 6 and a . doesnt work, have to wait until a time-out.

Should I press CTRL, the - and and shift and  6 at the same time?

Would it be possible to configure another key-combination? let's say CTRL SHIFT and Q ?

**Comment by kwinz** [comment]
@keithw Can you reopen this issue or should we create a new one?

**Comment by eminence** [comment]
Hi @kwinz -- can you clarify why you'd like to see his issue re-opened?  We recognize that the default escape sequence is not ideal on all keyboards/locales, but you've long been able to change the escape code (this is documented in the `mosh` man page -- see the section titled "Escape Sequences").

Do you want us to change the default?  Or are you unable to change the escape sequence for some reason?

**Comment by theAkito** [comment]
I'm a little bit appalled that there are so many recommendations for shortcuts, that only work remotely well on US keyboards. Most common PC shortcuts, especially the legacy ones from the old days before the year 2000, are extremely atrocious to type on non-US keyboards. I had problems with the Mosh shortcut for quite a while until I got a professional keyboard that was only available with a US layout, which makes things easier, regarding shortcuts on the computer.

So, can we not update the shortcut world a bit to the new reality? I had the same issue as @kwinz back when I wasn't using a keyboard with a US layout and even now, when I can use **CTRL+6**, it still kind of feels weird, because the system still expects **CTRL+^**.

That said, @eminence I did not know you could change the default. Still, there is no point in keeping an atrocious default and just pointing people to _oh you can just change it_. Especially, since it is best if software works as well as possible out of the box, without you being forced to change some really bad default option.

Therefore, I think it is just reasonable to change the default to something human and not keeping it as something weird. Especially, since `^` has already a special meaning for CLI users! Additionally weird and confusing!
Let's just change the default to something that actually makes sense...

**Comment by andersk** [comment]
To be clear, the system does not expect `Ctrl`+`^` or `Ctrl`+`6`, it expects the byte `\x1E`, and it actually has no idea which keys you pressed to generate that byte—that information is not made available to programs running in a terminal. There’s no reason to consider that weird. Every ASCII control byte can be generated via multiple key combinations:

* `\x00`: `Ctrl`+`@` or `Ctrl`+`` ` `` or `Ctrl`+`2` or `Ctrl`+`Space` or `Ctrl`+`/`,
* `\x01` through `\x1A`: `Ctrl`+`A` through `Ctrl`+`Z` or `Ctrl`+`a` through `Ctrl`+`z` (`Ctrl`+`H` is also `Ctrl`+`Backspace`),
* `\x1B`: `Ctrl`+`[` or `Ctrl`+`}` or `Ctrl`+`3` or `Esc`,
* `\x1C`: `Ctrl`+`\` or `Ctrl`+`|` or `Ctrl`+`4`,
* `\x1D`: `Ctrl`+`]` or `Ctrl`+`}` or `Ctrl`+`5`,
* `\x1E`: `Ctrl`+`^` or `Ctrl`+`~` or `Ctrl`+`6`,
* `\x1F`: `Ctrl`+`_` or `Ctrl`+`/` or `Ctrl`+`7`.
* `\x7F`: `Ctrl`+`?` or `Backspace` or `Ctrl`+`8`.

And of course, defaulting to any of these would likely have make someone mad because it’s in use by their favorite program. There are only so many bytes!

I’ve just gone and tested a variety of keyboard layouts (Arabic, Belgian, Chinese, English (international, UK, US), German, Japanese, Russian, Spanish), and `Ctrl`+`6` successfully generates `\x1E` on all of them, irrespective of where the `^` is actually located.

This may of course depend on your OS and your terminal emulator. If your terminal emulator is missing some of these sequences, perhaps you should file a bug there?

**Comment by theAkito** [comment]
@andersk 

It is weird to build in bytes into UX design. That is utter non-sense.

The user does not care which byte the program uses to differentiate whatever. The user wants to use the program and not create their own philosophy on what bytes the program will understand.

However, if CTRL+6 is correct on all these layouts, then it should be at least pointed out in the message on the top, when `mosh` disconnected. Nothing with `^`.

**Comment by keithw** [comment]
No -- the name (one name) of that character is Ctrl-^ (this is in the same language where "Ctrl-A" means 1, "Ctrl-B" means 2, etc.). See http://www.physics.udel.edu/~watson/scen103/ascii.html for the full table, including Ctrl-^. It wouldn't be correct to say Ctrl-6. But how you type it is up to you and your keyboard layout. The default escape sequence is not going to be convenient for everybody, which is why we added the environment variable to change it in. We did this in version 1.2.5, released in 2015.

**Comment by theAkito** [comment]
@keithw 

That's what happens when a hardcore backender tries to reason up user facing design.

To the user it does not matter if it is "_correct_". It has to **work**. Nobody cares, if it is technically the correct sign, the user just wants to know what he is supposed to do. He does not want to know how the program's code is written, just because he is using it.

Proceeding with this reasoning, it does not make sense to display ASCII characters in a text document, as in the end, it is saved as bits on the disk. So displaying these characters is "not correct".

As already said, even if the default is variable, it does not change the bad situation of the current default. That does not make the default better.

So _even if_ the default does not change, the message should at least show something that **makes sense**. (No -- showing what the code thinks, is not something that makes sense to the user, see segfaults as a very rough example...)

**Comment by keithw** [comment]
@theAkito The truth is that there are multiple principles at play here.

One valuable principle is the idea of making things as easy as possible for users who, as you say, don't really care to master the tools (or read the man page or FAQ) but just want software to work without bumping into anything unpleasant.

Another valuable principle is the idea of modularity and trying to behave predictably so that users can compose Mosh and expect it to behave predictably. Mosh is a somewhat normal "command-line" program that tries to play well in the ecosystem; it does not "own" your keyboard input (it doesn't know what layout you are using or how you generate the bytestream it sees; it just accepts the bytes you give it), and it doesn't "own" your display (it doesn't pop up a window on your screen). We don't want Mosh to know these things or try to take over more of the ecosystem. Mosh interfaces with other programs using international standards (in this case, ASCII and ECMA-48), and we use standard nomenclature (e.g. "Ctrl-^", with a lot of handholding for how to type that and how to change it) for what we expect from the user.

So: we have an FAQ entry about how to type this, we have text in the manual page about how to type this, and we have guidance on how to change it if it is inconvenient for you... We're trying to meet you at least halfway here! :-) But if you think this needs to be immediately accessible without doing anything unpleasant on your end (including reading the FAQ or the manual), I'm afraid Mosh is not trying to win your business and may not be willing to make the kinds of compromises necessary to get there.

**Comment by theAkito** [comment]
@keithw 

In case I was misunderstood: you are right all along. I don't want to say that you are incorrect. Never meant to say that. All I am trying to say, is that the user has to understand what to do so the program behaves the way they want to.

The problem with the FAQ etc. you mention is that the user has to look up something if they just want to use the program. But if they want to engage further in it and do something more advanced, which would maybe require some advanced knowledge to begin with, anyway, they don't have to look up this little thing?

So all I am trying to say: just show CTRL+6 in the banner. Then, if someone is interested or needs predictability, any of the advantages of truth that you mentioned or anything advanced for advanced users only, THEN they can look it up and then the FAQ should say "_We show CTRL+6 for easier usage, but it is actualy byte XX_.". I would find this much more reasonable from a UX perspective.

Especially, since your last post shows, that you are very knowledgeable on this topic. Which is great. So maybe for your the 

> standard nomenclature

is pretty standard and pretty self explanatory. But I assure you, for most normal users, that is something they never heard of.

So my opinion is, that it is better to display something that nerds, experts, beginners and other people understand instead of something only nerds and experts understand, where the only consequence would be that some nerds would complain about it not being technically entirely correct (since, in this scenario, they could look it up in the FAQ anyway, if they wanted to know about it precisely).



P.S.:
To sink in the final nail into my statement's door to understanding:
Due to me having to work with the CLI day these symbols weren't new to me. However, since I used a non-US keyboard for the most part of my life, I never bothered with handling any advanced combos, as there was no point to it on that particular keyboard, where it is particularly hard to type certain symbols.

In the following particular case, I did not know that CTRL+6 equaled the same byte as was requested by mosh.

So here is what happened:
1. My server had a connection issue.
2. Mosh asked me to do a combo.
3. Didn't know how to solve that on my keyboard.
4. I need to reconnect, not fiddle around.
5. I close the terminal.
6. I open the terminal and reconnect.
7. `mosh` point broken. I could use plain `ssh` if I repeat this procedure.

This happened a lot of times, but I could never fiddle around with that key to _actually_ press, so I can reconnect or close the connection for good or whatever, because I needed to continue to work on the server.

I imagine that happened to a lot of people, especially with a non-US keyboard layout. All this could've been avoided entirely with a banner telling me _"Hey buddy! Just press CTRL+6!"_.

However, if I was interested in the actual byte, I could've visited the website when I'm free to do so, to read the FAQ regarding this byte. That way, everyone should be happy, in my opinion.

P.P.S.:
Again, you are _technically_ correct. I am talking from a design perspective, not from a technical perspective, since we have already a lot of very high skilled technical people here.

**Comment by dawidi** [comment]
Here, have another vote on this eight-year-old issue, for adding something like "(alternatively, Ctrl+6 .)" to the banner message. It'd be a really simple, user-friendly and side-effect-free solution to a significant usability hassle.

I'm using mosh only on one server with a particularly flaky connection, and every time I run into problems there (which is about once every 6 months so I've almost forgotten I'm even using mosh) I keep coming back through google to this issue in order to look up what the alternative key combo was.

(And I've been fiddling around enough with ancient serial terminals recently that I am indeed aware of the relationship between Ctrl and the lowest 32 ASCII byte values...)

**Comment by sberney** [comment]
I am used to `^` being the meta character for control, so I didn't understand the message `Ctrl-^ .`, it seemed to be redundantly saying to press ctrl, and then `.`. And "what is the `^`" is pretty close to ungooglable. I immediately ruled out that it was a literal `^`, since that is not a normal way to escape a program, and it usually indicates a meta character.

... Anything would be better IMO.

**Comment by peterbraden** [comment]
> I think, honestly, my thinking on this has changed and I would be open to moving to `RET ~ .` in a future major Mosh version. If somebody wants to prepare a pull request, it would be favorably received.

I got bitten by this today - would a PR to change default to `RET ~ .`  still be accepted?

**Comment by eminence** [comment]
> I got bitten by this today - would a PR to change default to RET ~ . still be accepted?

To be honest, no I don't think we would accept a change for the default escape code at this point.  I recognize the default is not ideal for some people (and I myself ran into this yesterday), but is it not possible to find a default that is perfect for everyone.  Remember that you can change the escape key (see the `mosh(1)` man page), so I definitely recommend finding something that makes sense for your keyboard and your environment.

**Comment by POMATu** [comment]
Ok i read whole thread precisely and manual too I tried every damn combination and finally i got it working with **RET ~ .**
This is so confusing that I made a riddle for you:
**_How much *nix junkies you need to close a single mosh session?_**

Just think about it I would be perfectly fine with typing **/mosh_close** or anything else that is less **obscured**

**Comment by keithw** [comment]
Sorry to break it to you, but if your escape sequence is "RET ~ ." out of the box, you aren't using Mosh. That's the default escape sequence for OpenSSH.

For Mosh, the default escape sequence to close a connection is Ctrl-^ (meaning ASCII 0x1E, sometimes typed by holding Control and hitting the "6" key but it depends on the keyboard) but it's configurable with the MOSH_ESCAPE_KEY environment variable if you want something else.

**Comment by andersk** [comment]
@POMATu A problem with setting the combination to something like `/mosh_close` would be that, in order to allow that to work without sending junk to the inner application, Mosh would need to temporarily freeze the keyboard input if the user typed any _prefix_ of this combination. For example, if a user started typing `cd ~/src/mosh`, their shell would only receive `cd ~/src`, because after that, Mosh would have to assume that the user might be in the middle of typing `/mosh_close`. Of course, Mosh may eventually realize this is not what’s happening and release the buffered input if the user types something else (e.g. if they press Enter after `/mosh`), but by then there will have been a notable lag and the user might already be confused about why their shell is not responding.

Furthermore, the user might really want to type `/mosh_close` into the inner application—for example, if they’re running an IRC client inside Mosh and trying to teach an IRC user how to close Mosh, or if they’re running Mosh inside Mosh (yes, people do that), so there always needs to be a way to pass the combination through to the inner application.

I know that `/mosh_close` was just an example, but the same argument applies to *any* combination one might like to use (including `RET ~ .`). That’s why it’s important for the combination to be “obscure” and unlikely to conflict with existing applications, and for there to be a reasonable scheme for passing the shortcut literally (Mosh by default uses `Ctrl-^ ^` to pass `Ctrl-^` through to the inner application). Hopefully this helps explain why the default was chosen the way it was.
