### ISSUE TITLE
Autofailover to a 'regular' shell?

### ISSUE THREAD

**Issue by rizwank** [mobile-shell/mosh#232]
Since mosh-client connects to the target server; and then runs mosh-server; would it be possible to have it revert to the already connected SSH shell rather than disconnecting? Would be great to alias mosh to ssh (well, assuming there are no other ssh arguments to pass.)

**Comment by anarcat** [comment]
gosh yes. although there seems to be two distinct issues mentionned here:

* fallback to `bash` if `mosh-server`is not present, the *remote doesn't speak mosh* scenario
* fallback to `ssh` if we can't talk to `mosh-server` on the network, the *can't connect through the firewall* scenario

those are two totally different issues, and I feel the former can be addressed with wrapper scripts (and should be fairly easy to implement), the latter sounds a little more complicated as it involves timeouts and back and forth communication.

anyone working on this?

**Comment by minhoryang** [comment]
+1 Please God

**Comment by ColdHeat** [comment]
I ended up throwing the following into my zshrc. 

```
ssh() {
    if ! [ -x "$(command -v mosh)" ]; then
        echo "mosh client not found."
        command ssh "$@"
    else
        echo "Found mosh client."
        command mosh "$@"
        [[ $? -ne 0 ]] && (echo "mosh server not found" ; command ssh "$@")
    fi
}
```

Still has the problem of two connections if mosh isn't installed on the server unfortunately though.

**Comment by L3vi47h4N** [comment]
+1 on autofailover feature. Main reason I don't use MOSH at work.

**Comment by hupfdule** [comment]
Still waiting for SSH failover.
The above mentioned scripts are not even a real workaround when using password authentication or not using ssh-agent.

**Comment by mrusme** [comment]
Just in case anyone here would prefer a more efficient way to do this, check out [my .zshrc](https://github.com/mrusme/dotfiles/blob/master/.zshrc):

https://github.com/mrusme/dotfiles/blob/dbb63bc1401f9752209296b019f8b362b42c1012/.zshrc#L358

The `ssh` function checks the `~/.ssh/config` file for a comment that starts with `# Features:` and includes `mosh`. Based on that it decides whether to use `ssh` or `mosh`. This way it won't first blindly try `mosh` and use `ssh` as fallback, which would take too much time for every connect.

An example of how your `~/.ssh/config` might look like:

```cfg
ServerAliveInterval 60
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_ed25519

# Features: mosh
Host host1
  HostName host1.domain.com
  Port 9876

Host host2
  HostName host2.domain.com
  Port 8765
```

As you can see, `host1` has the feature `mosh` enabled, hence the `ssh` function would connect using `mosh`. `host2` on the other hand has not, hence the `ssh` function would connect using regular `ssh`.

Right now the function only checks for a `mosh` connection when its called with a single argument (e.g. `ssh user@host1`), in order to avoid trying `mosh` for things like `ssh -L 1234:localhost:2345 user@host1`. This could be refined to handle more cases in the future though.

Hope this helps.

**Comment by achernya** [comment]
Closing in favor of #188 which looks like it will solve this issue in a cleaner way.
