### ISSUE TITLE
windows client

### ISSUE THREAD

**Issue by ericsnowcurrently** [mobile-shell/mosh#293]
What is required for a windows client (native, not cygwin)?

**Comment by cgull** [comment]
I had a look at @micolous' fork.  As it stands the code is not ready to pull-- files are duplicated & modified, `#ifdef WIN32` is liberally sprinkled, the new Windows code has essentially no comments.  But it didn't seem fundamentally broken.  Also, I'd guess the slowness issues are more about the Win32 GUI's display code than anything in Mosh itself.

Just my opinion, but if someone who knows Windows and platform issues better than I were to spend some time cleaning up the source and cleanly breaking out the ifdefs into separate platform code, that might be well received.  I don't know a lot about Windows development, but I suspect MinGW might be an easier/cleaner port for Mosh than the plain Win32 environment.

**Comment by timofonic** [comment]
@cgull 

Hello.

Are there news about this?

I would love to deploy Mosh on several machines, but lacking a free and easy to use Mosh client on Windows is an issue to me.

Maybe you already looked at this:

http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/mosh.html

Kind regards.

**Comment by micolous** [comment]
@timofonic If you want to use mosh on Windows _today_, _easily_, I would strongly encourage you to look at [mosh-chrome](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj?hl=en).  It has matured greatly in the last couple of years to the point that I wouldn't bother using PuTTY.

@cgull You may wish to edit the original bug posting to mention the Chrome app version, and maybe amend the website to indicate that the Chrome app is the easiest way to run it on Windows.

The code there is written by @ipkn, so unfortunately I cannot shed further light on how it's works or it's style. :disappointed: 

**Others**, it is known there is _demand_ for a Windows mosh client, but there is nobody with sufficient knowledge to step up and finish this work.  There is no need to constantly spam the bug with "+1" or offering to test it.

**Comment by timofonic** [comment]
@micolous 

Sorry, but I use Pale Moon on all my systems. I disagree to use Google Chrome/Chromium.

I can't find one for XUL/Pale Moon. I agree a web client could be interesting for some use cases, but a native app would be preferred.

PuTTY authors = stoneheaded +MIT/BSD license = forking hell. 

The only usable and flexible alternative for Windows seems to be MobaXterm (I fail to understand why there's a zillion of putty forks and console emulators instead merging efforts to make a multiplatform version of that, it uses forks of PuTTY and others.

[WinSwitch](http://winswitch.org) (a GUI wrapper for xpra, NX, VNC, RDP, ssh X display forwarding) seems near of MobaXterm, but lacks console and MOSH support :(

**Comment by cgull** [comment]
@micolous, @timofonic, I think it's **extremely** unlikely that PuTTY will ever support Mosh as part of the core `putty.exe`.  Its authors are very conservative about changes, because it's security software.  (So are we.)  Running mosh-client as a backend process in conjunction with PuTTY seems more plausible.

Actually, if you like the way PuTTY works, consider using Cygwin, mintty, openssh, and Mosh-- mintty is derived from PuTTY source.

As for a Windows port-- it seems that none of Mosh's developers has had an interest in doing that, and nobody has yet brought forth work that we can use.

Just to be clear-- the work that @ipkn and @micolous did looks like a good start, though.  It seemed reasonably well designed, and I didn't see changes to core Mosh code that would be unworkable.  The issues I saw seemed like they were all fairly easily fixable with some time and attention; I'd encourage any developer who's interested in a native Windows Mosh to take a look at it and start a discussion about what would need to be done to integrate it into core Mosh.

**Comment by timofonic** [comment]
I summarized the ["MOSH TO-DO"](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/mosh.html) just for easier future discussion:


**Summary:** Compatibility with Mosh (mobile shell)
**Class:** _wish_: This is a request for an enhancement.
**Difficulty**: _taxing_: Needs external things we don't have (standards, users etc)
**Priority:** _low_: We aren't sure whether to fix this or not.

Several people have asked us to extend PuTTY to add compatibility with Mosh, a rather unusual remote-terminal application that's particularly suited to use over bad networks. 

This is a tempting idea in principle, but there are several practical problems:

- ☒ The used SSP (State Synchronization Protocol) doesn't seem to have any public documentation.
 * It makes difficult to write another implementation.
- ☒ It doesn't transport a terminal stream, updates the screen by other means. 
 * This isn't like all the protocols currently supported by PuTTY.
 * Adding support would need hooks into the middle of the current monolithic terminal emulator, becoming a fairly large amount of work.
- ☒ It's use of the network is very different from all our existing backends, which use small numbers of TCP connections.
- ☑ It does require an SSH client implementation for authentication and key-exchange. 
 * There are some major parts of PuTTY that could be re-used.
- ☒ It uses OCB, patented in the USA.
 * There are fairly generous licences available for the relevant patents, but some not ones as PuTTY's copyright licence and specifically in proprietary software in military use.
   * [The OCB's patent licensing model](http://web.cs.ucdavis.edu/~rogaway/ocb/license.htm)
 doesn't authorize any military use of it. 
 * What about other alternatives? [GCM (Galois/Counter_Mode)](https://en.wikipedia.org/wiki/Galois/Counter_Mode), [CCM Mode](https://en.wikipedia.org/wiki/CCM_mode)?

- `It's possible that someone could write a patch to add Mosh compatibility to PuTTY that we'd be willing to accept, but it's not the most likely thing ever.`
* Will this be always true?

**Comment by cgull** [comment]
@rpwoodbu has adopted https://github.com/rpwoodbu/mosh-chrome to a single-package, native Windows install with no dependencies.  This looks like it might be a very good solution for Windows users.  I urge people to try his early builds and give him some feedback.  See the discussion and download links towards the bottom of https://github.com/rpwoodbu/mosh-chrome/issues/127.

It also looks like he might be about to push a 0.4.0 release, so check for that too.

**Comment by Zenexer** [comment]
For those of you looking for a native solution, msys2 does offer a mosh package.  I've been using it with ssh-pageant, Gpg4win, and a smart card without issue for some time now without issue.  The default terminal emulator is mintty, which is based on PuTTY's terminal emulation components, but there are plenty of other options available.

It's also worth noting that Windows 10 Anniversary Edition offers [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about), which does support mosh inside cmd.exe.  However, it's a bit more difficult to deploy at scale, and there's little to no chance you'll get it to work with a smart card.

**Comment by rpwoodbu** [comment]
@Zenexer Re Mosh for Chrome performance: Take another look. In the early days, it did have some performance issues, and occasionally would get into a funk and take all the CPU. I don't think that's the case anymore (but if so, please report on the mosh-chrome project). The terminal emulation (not my code) has also improved, and is quite good these days.

I would greatly appreciate any feedback on the Windows port that @cgull mentioned. I do intend to release it in a few days barring any bug reports.

**Comment by Zenexer** [comment]
@rpwoodbu It's not really an issue with Mosh for Chrome or the terminal.  The issue is that anything Chrome-related gobbles battery on Mac, Linux, and Windows (but seemingly not ChromeOS).  That includes Electron apps, too, although Visual Studio Code seems to be better than most.  JS desktop apps wrapped in Qt have the same issue.  Such apps--including Chrome--are always the number one cause of battery drain on my Mac, Linux, and Windows devices.  If I have to go an extended period of time on a single charge, I have to keep web-based apps closed.

For example, at this moment, the top CPU hogs on my laptop are:

* Slack (MacGap)
* HipChat (Electron)
* Telegram (recently added Qt web controls)
* Chrome

All of those are "closed" (in the Mac sense) with the exception of Chrome, meaning they're not in the foreground and there's no visible window, yet they're each consistently using 1-4% CPU.  That's a lot when you need to work for an entire day without charging.

**Comment by cgull** [comment]
This is wandering off topic, but Mosh itself is not the best thing for battery life.  It sends/receives a message every 3 seconds and (especially in versions before 1.2.6) is computationally intensive compared to SSH, even when idle.  The constant messages are probably the more significant problem currently, because that can cause radios to be brought up/shut down to transmit the messages constantly.

Mosh for Chrome performance should also have improved because it now has Mosh 1.2.6, though.

**Comment by Zenexer** [comment]
Actually, I haven't really had any issues with battery drain while using mosh from msys2, Homebrew, or Arch.  Some terminal emulators will use a lot of power if there are frequent updates, though (e.g., iTerm2).

**Comment by pratham2003** [comment]
Would it be possible to implement Mosh's protocol using javascript?
https://electron.atom.io/

**Comment by cgull** [comment]
Yes.  But you'd need an OCB implementation and UDP sockets, and you'd have to reimplement some fairly tricky, idiomatic C++ code.  Mosh has been reimplemented before (in an Android app).

**Comment by rpwoodbu** [comment]
Doesn't the Android app actually just use the C++ Mosh code? 

In case you missed it, @pratham2003, Mosh for Chrome is now in a beta version as Mosh for Windows.

**Comment by Zenexer** [comment]
My biggest beef with Mosh for Chrome (and similar apps) is that they don't offer integration with GPG through the ssh-agent or putty-agent protocols.  I haven't gotten it working with the msys2 version, either, though it should be possible.

**Comment by rpwoodbu** [comment]
@Zenexer This is harder than it sounds. The Chrome sandbox is quite strict. However, there _is_ a way, and it may even be appropriate now that there's a "native" Mosh for Windows.

The only way (that I'm aware of) of escaping the Chrome sandbox is to use [Native Messaging](https://developer.chrome.com/extensions/nativeMessaging). This makes it possible to communicate with a native app from a Chrome app (or extension). At that point, pretty much anything is possible. But registering a native app (even one that is already installed) requires installing a file in a magic location (or writing a registry key on Windows).

I never bothered with any of this, because the primary use-case was Chrome OS, and other platforms had native solutions... or so I thought. It wasn't until recently that it became apparent to me that Windows users didn't have a great native solution, and many were using Mosh for Chrome. That's why I was willing to make Mosh for Windows (which is really just Mosh for Chrome bundled with the Chromium browser in a native installer).

Since there's a native installer, there's a mechanism for registering a native app, and even delivering that native app should a proxy be needed between Chrome and ssh-agent. On top of that, there's already some ssh-agent support in Mosh for Chrome (via a 3rd-party Chrome extension, not really for public consumption). So a motivated individual could hack this up fairly easily.

**Comment by voronoipotato** [comment]
My biggest beef with using chrome is that it installs a virus checker that is difficult to remove, which scans your system every week and god knows what it reports back. I would prefer basically any other solution.

https://motherboard.vice.com/en_us/article/wj7x9w/google-chrome-scans-files-on-your-windows-computer-chrome-cleanup-tool

**Comment by rpwoodbu** [comment]
This solution is based on Chromium, not Google Chrome, so that should assuage your concerns.

I will also take this opportunity to note that Chrome OS is getting the ability to [run Linux VMs](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook), which may make this app obsolete for Chrome OS. That would mean the only remaining use case is Windows. I'm not a Windows user, so...

**Comment by zakius** [comment]
I wish for something that can be ran in my cmder, currently I'm using WSL for that but using whole WSL just for that is an overkill
being able to build mosh as is for windows would be ideal

**Comment by voronoipotato** [comment]
Yes also not everyone is on windows 10. Using cygwin, or WSL is not actually a solution. Mosh is literally the only reason why I use chrome.

**Comment by nanonyme** [comment]
@micolous just a thought: what if it wasn't integrated directly with PuTTY at all? PuTTY project has a command-line SSH client implementation called plink and Windows 10 now ships with SSH. Windows builtin terminal is now also getting a lot better so it might be worth it these days to have a Windows version of mosh that would use external SSH for secret exchange and normal native terminal for terminal purposes (same as on Linux). Just my two cents.

**Comment by ShinobiWPS** [comment]
@nanonyme totally agree.
It seems to me there is a lot of hope with increasing support to have more and more UNIX/Linux-like utilities convenient in the more seamless way.
Talking for my self, I'm using PowerShell instead of something else since every binary I install I do want to be available in my PATH.

**Comment by zakius** [comment]
@nanonyme actually built in SSH is somehow broken, doesn't set proper TERM causing things like mc to flash constantly while every other windows build of OpenSSH works just fine, though sooner or later it will mature

I'd say: just use whatever ssh is available in PATH, not relying on the built in in any way

**Comment by nanonyme** [comment]
Sure. Primary method ssh from PATH, secondary eg MOSH_SSH would probably work fine

**Comment by zakius** [comment]
Windows is getting PTY next release (and up to date insider builds have it already) if it changes anything in terms of porting/building Windows binary

**Comment by musm** [comment]
Also windows now includes native openssh, can that not be taken advantage of here?

**Comment by Lockedev** [comment]
I think Windows Terminal (and the related work being done at by @microsoft/terminal) might make this more viable..?

**Comment by tallship** [comment]
Well it's not working for me but **_there is this_**:

![mosh_fail](https://user-images.githubusercontent.com/561994/70526438-67942980-1afe-11ea-9e14-50d7a218cf8b.png)

I hope that helps :)

**Comment by mbirth** [comment]
MobaXterm is using cygwin, so it's not native.

**Comment by daef** [comment]
does mosh maybe work with [windows terminal](https://github.com/microsoft/terminal) ?

**Comment by TuxGamer** [comment]
I can confirm that mosh (client) works perfectly with WSL. I am using the old CMD though and have not tested Windows Terminal

**Comment by daef** [comment]
Yeah, WSL has been mentioned multiple times . I won't let that go though as native thou ;)

This windowsterminal thing seems to be UWP, which I guess is the new *native* (I'm not sure if UWP was already around when the question was asked...)

**Comment by kellytrinh** [comment]
WSL is very lightweight and basically MS did enough in terms of syscall compatibility to have it work so well; not sure if insisting on more before letting go adds any more value.

**Comment by Zenexer** [comment]
I've been using mosh via WSL for a while now.  It's works well enough, but it's a pain to establish a connection if you want to use ssh-agent or gpg-agent from Windows.  The only way I've found to get it working is to ssh in from Windows, manually start mosh-server, and copy the key over to WSL.

**Comment by zakius** [comment]
of for whatever reason you can't use WSL1 (home variant) nor WSL2 (unavailability of H-V) you can't use mosh at all (okay, you can use cygwin build I think but that's still less than ideal)

so while not high priority it would be nice to have one that *just* works

**Comment by aress31** [comment]
+1

**Comment by rashil2000** [comment]
For the mosh-client, native Windows builds are available - https://github.com/jumptrading/mosh-windows-wrappers

These are used by Fluent Terminal.

**Comment by achernya** [comment]
It looks like most folks have moved away from cygwin and towards WSL which has "native" mosh.

**Comment by ethindp** [comment]
Is there any update to this? I don't mind using WSL, but I would like a native client I can just fire up without needing a VM to do it.
