### ISSUE TITLE
"Invalid argument" when binding

### ISSUE THREAD

**Issue by massemanet** [mobile-shell/mosh#335]
So I'm trying (and failing) to connect to a crappy old server running debian 5.0.10 (kernel 2.6.16.16).
On the client side (macos 10.7 + brew) I see this;

$ mosh 10.0.1.14
Failed binding to 0.0.0.0:60999
Error binding to any interface: bind: Invalid argument
Network exception: bind: Invalid argument
Connection to 10.0.1.14 closed.
/usr/local/bin/mosh: Did not find mosh server startup message.

Trying to start mosh-server by hand results in this;

$  mosh-server new -v
mosh-server: network.cc:275: Network::Connection::Connection(const char_, const char_): Assertion `false' failed.
Aborted

$  mosh-server new -v -i 10.0.1.14 
Failed binding to 0.0.0.0:60999
Error binding to any interface: bind: Invalid argument
Network exception: bind: Invalid argument

I'm not savvy enough to track this down. Advice appreciated.

**Comment by tokyo-jesus** [comment]
I am seeing this same issue. I am running Ubuntu 15.04 in a Linux-branded zone.

```sh
>>> mosh self@8b490c8f-107c-67aa-f2f1-f33afb568bb1
Network exception: setsockopt: Invalid argument
Connection to 8b490c8f-107c-67aa-f2f1-f33afb568bb1 closed.
/usr/local/bin/mosh: Did not find mosh server startup message.
```

**Comment by cgull** [comment]
So if my Google fu is any good, you're running a Linux container on a Solaris/Illumos/SmartOS kernel.  You may be a bit on your own here...

Can you describe your environment a little better-- host OS, contained OS, mosh-package?  A `uname -a` from an emulation environment is not incredibly helpful, unfortunately...

The simple fix would be straightforward, change that error check to not kill mosh-server, but it's there for a reason.  If we can find a better solution, that'd be good.

**Comment by tokyo-jesus** [comment]
Yeah, I wasn't sure what information would be useful.

I'm running an "infrastructure container" on SmartOS. The container
image is Ubuntu 15.04. I installed `mosh` via `apt-get` on the server.
My local machine is running OS X with `mosh` installed via homebrew.

**Comment by cgull** [comment]
First, @tokyo-jesus's problem is actually completely different from the problem this issue was opened for, though the error messages are similar. 

After some thought, I think this is an emulation failure on the part of SmartOS.  If it claims to be Linux 3.19, it should provide the functionality that glibc expects from a real Linux 3.19 kernel.  I suggest reporting this as an issue against SmartOS or Illumos, whoever is the upstream that's responsible for the Linux emulation.  Use `strace` or `truss` with `mosh-server new` and include that in the report.

Admittedly, this is a messy problem for emulators; glibc handles many missing syscalls itself, but ioctl() and setsockopt() are a much harder problem.

I also think Mosh is sometimes overly strict in its handling of errors, and exits in some cases where it would be reasonable to continue.  I'm not sure whether this error is one of them; that depends on what PMTU+UDP behavior we'd get on systems that return this error.
