### ISSUE TITLE
reattach to detached mosh sessions

### ISSUE THREAD

**Issue by ghazel** [mobile-shell/mosh#394]
Sometimes after a crash/reboot of my client machine, I see "Mosh: You have a detached Mosh session on this server (mosh [12726])." when I log back into the server. It would be nice to be able to reattach to that session.

**Comment by pdostal** [comment]
I use @hboetes solution with `$1` instead of `$t` as an `remosh` alias

**Comment by hinesmr** [comment]
To my amazement, I used CRIU (https://criu.org) to checkpoint and restart a mosh client and it worked.

Shocking.

**Comment by cgull** [comment]
This sort of thing has been around a really long time (see:  Emacs dump/undump) and mosh-client is actually an excellent candidate for it.  It doesn't have any stateful interaction with files, and while networking is a lot more complicated, mosh-client strangely enough is more than willing to tear it all down and set it up again when it isn't working.

Hmm.  If you look at it just so, this is a new attack surface on Mosh, enabled by its very simplicity.

**Comment by hinesmr** [comment]
This method would likely also hands-down enable https://github.com/mobile-shell/mosh/issues/608 too ( migrating mosh clients from one machine to another). 

This would already be done by running mosh-client inside of a virtual machine anyway --- while being less convenient, I don't think that lowering the attack surface is the way to go here.

If both virtual machines and CRIU make this a non-issue, there must be some middle ground in terms of security........ but the security experts need to comment on that.

**Comment by andersk** [comment]
Your ability to run your own Mosh client inside a virtual machine or CRIU does not constitute a new attack surface (you are not attacking yourself). I recommend against it, though, because using one of these technologies to accidentally duplicate your client process or restore an earlier version will lead to [reuse of a cryptographic nonce](https://github.com/mobile-shell/mosh/issues/608#issuecomment-107780228), compromising your session’s security. I don’t see a way for Mosh to stop you from [shooting yourself in the foot](https://github.com/mobile-shell/mosh/issues/608#issuecomment-108170879) like that, so at least be very careful when using these loaded guns.

And there are still some issues to be solved when migrating a client to another terminal, especially if its properties differ from the original terminal’s (e.g. BCE support, number of colors).

**Comment by cgull** [comment]
From a theoretical perspective, there's no new attack surface; from a practical perspective, CRIS makes it rather easy to steal or copy a user's Mosh session on a rooted machine, and even transport it to another machine.

mosh-client is an "excellent candidate" for checkpoint/restore because it's an easy application to apply checkpoint/restore on, and not because it's a good idea to actually use it that way, for the reasons @andersk points out.

**Comment by hinesmr** [comment]
@andersk CRIU doesn't duplicate anything ---- it kills the original process and saves all its state to storage. My laptop (personally) is encrypted (even my cell phone), so I'm confident in CRIU not increasing the attack surface. As long as there is only one copy of the nonce in existence at any given time and its only accessible by me, then it seems fine.

**Comment by RubenKelevra** [comment]
I badly wait for this feature, see no security issues at all here, if a new ssh-session is created, a new secret can be exchanged with the server, so the old client can't reconnect to this session.

**Comment by msva** [comment]
guys, why don't you all want to just use tmux/screen?

**Comment by zamabe** [comment]
Probably because that's not automatic. Convenience is king, and there is no mosh-specific autoexec to jump into the latest tmux screen/create one.

**Comment by hinesmr** [comment]
Right, if it weren't about convenience, I don't think this ticket would be open. =)

Of course there are other, less convenient solutions that require more typing.

**Comment by msva** [comment]
yeah, some kind of .moshrc with per-hosts "exec" would be nice, but I think it is another issue ;)

**Comment by zamabe** [comment]
Indeed, asking why people won't use tmux is a very different question than why they want mosh reconnection to dropped sessions.

**Comment by msva** [comment]
Asking "why don't they use term muliplexers" following their answer on "why do they want security-breaching feature of reconnection to sessions with lost local session keys". Most answers is about reconnecting to previously used pts. And, as said in beginning of the topic, that is what term.multiplexers for, but not `mosh`. `mosh`'s case is like `ssh` one. And as you can notice, `ssh`, doesn't allow you to reuse pts used by another session (even if it is already dead, but not yet killed by timeout).

Proj. members also telling you that all imaginable at current moment ways to implement session reusing introduce potential security breaches (creates target for session keys stealing attacks). So, yes, using term multiplexers (which is designed for that) is about to more typing, but, hey, don't you type the same when using just `ssh`?

// and you still can place it in `~/.{ba,z,fi}shrc` or even `~/.profile`

**Comment by andersk** [comment]
@zamabe: Here, aliases for your `~/.bashrc` to automatically attach, or create if necessary, a remote screen or tmux session via mosh:

```sh
mosh-screen () {
    mosh "$@" -- screen -dR mosh-session
}

mosh-tmux () {
    mosh "$@" -- tmux new -ADs mosh-session
}
```

There’s no magic here—all the necessary logic is already built into screen and tmux. See their manpages for more detail.

**Comment by zamabe** [comment]
@andersk I already just use `mosh -- machine tmux attach`, and having local aliases does not address my comment(s) because 1) You still have to explicitly choose to change the command you're using (and so I'll stick with the explicit ones); 2) This is something that is more convenient for remote-side specification.

Regarding 2; I may not care whether my job is unrecoverable on some system, but I do on another. Having the option to have mosh do a .moshrc when I connect to the remote which could set some things and pull me into a tmux session **by default** means that I no longer have to have special behavior as a user. Convenience wins, and I'll never kick myself for losing control of a *really* important job.

**Comment by hinesmr** [comment]
@zamabe :+1:

**Comment by pmitros** [comment]
@keithw I understand you see this as academic, but would you see it as a security issue if this were: 

1. A thin wrapper around something like screen, rather than a fundamental change to the protocol? 
2. Only possible if explicitly enabled in a config file/command line parameter. 

All old security tokens go away, and new ones are created. 

Basically, optional syntactic sugar.

**Comment by RubenKelevra** [comment]
There's no security issue at all since the first and second user are both authorited via SSH they just need to exchange a new token for the old session and do a screenrefresh. I don't see any security concerns like on mosh ssh key forwards. You have to make sure the users know what they are doing, so print a warning and implement this very productive feature.

**Comment by RubenKelevra** [comment]
So @keithw please reopen since this is still not implemented.

**Comment by kentmartin73** [comment]
Hi - I'd love to see this reopened as well.

Having this available as a config option which is off by default seems to make perfect sense to me.   A nice big description of the potential security issues in the distributed config file, and, the same description at the relevant place in the man page.

'twould make myself and others smile I'm sure, and smiles are good!

**Comment by yaroslavvb** [comment]
Security reasons are mitigated when used under VPN (ie, any user on VPN already has sudo access to machines on cluster), it would be useful to have a configuration option to relax security check for such scenario

**Comment by blazespinnaker** [comment]
Screen and tmux have baggage that cause issues in different contexts.  Why not just have a flag that allows for reconnecting?  The whole point of mosh is to provide reliability over unreliable connections.  Power outages and crashing computers (or iPads) seems a part of that.

**Comment by daviddelikat** [comment]
I feel that the added complexity of a re-attach feature would be wasted effort and provide more opportunities for problems in addition to the security issues; developers would have to deal with much of what tmux and screen already do very well.   ...  the best solution for lazy people is to write a script or function; @andersk provided some nice ones.  ...  I think a discussion about a server cleanup feature would be a more profitable discussion; though I suspect it's an unreasonable problem to solve.

**Comment by dgentry** [comment]
Laptop crashed, reconnected to the remote machine, mosh says I have 4 detached mosh sessions, I have to search for the fact that I can't do anything with them except kill them (and to add insult to injury, I have to transcribe several annoying numbers to kill them).  So that experience sucked.

This is an opportunity to do something a lot simpler than tmux or screen.  

Why would it not work (securely) for the client to checkpoint the mosh connection's state to disk, encrypted using the public half of the private key we use to connect to the remote mosh server?  Then to reconnect, decrypt the state using the private key we need to connect to that server anyway.

**Comment by andersk** [comment]
@dgentry Mosh uses no public-key cryptography (except in that the `mosh` wrapper script invokes `ssh` to establish the initial connection and start `mosh-server`). In any event, although on-disk encryption is more or less a solved problem, the security concerns here are more subtle than an attacker directly reading the state while it’s sitting around on your disk. Additionally, there are non-security issues complicating the implementation of migrating the terminal state to a new terminal.

To quote the [relevant comments at #608](https://github.com/mobile-shell/mosh/issues/608#issuecomment-107780228):

> **andersk** commented on Jun 1, 2015
> This feature request scares me from a cryptographic perspective. The mosh-client internal state includes a cryptographic nonce that must never be reused, and I worry that if you allow the state to be serialized, it would be hard to stop users from unknowingly compromising their own security. We could solve this by adding a way to negotiate a new session key for each resume, but that means protocol changes and extra security-critical complexity.
>
> Also, from a terminal perspective, the existing C-^ C-z support is incomplete (e.g. #505), and such problems would be compounded if mosh-client was allowed to resume on a different terminal.

> **cgull** commented on Jun 2, 2015
> Now that @andersk has explained his worries, I'm scared too, because I can easily construct a foot-shooting scenario that doesn't even need any help from your friendly local nation-state surveillance agency:
> - user detaches original mosh client, gets session state, copies it
> - user tries to attach with new mosh client, pastes state, startup fails for whatever reason (probably network connectivity), but in a way that has traffic observable by an adversary.
> - user goes "Huh...that didn't work", repeats on his other phone.  **Oops**.
>
> The Perl argument doesn't hold much water, since it's already been rewritten at least twice in C/C++, and in this scenario you might just as well use mosh-client directly anyway.
>
> And it seems to me that there's a workable already-secure and already-available solution to this problem:  Use screen/tmux.  On your existing mosh session, start a new mosh-server.  Convey the key/IP/port you get from this server to the new device, the same way you'd have copied the entire session state.

It’s easy to say “well why don’t you just [one sentence]”, but it’s hard (maybe not impossible, but hard) to actually come up with a full design, implement it, and justify the risks associated with the inevitable complexity increase.

**Comment by eskhool** [comment]
@andersk, for those of us without the relevant security concerns of the snooping local govt or don't think this is enough of a security risk...why not let us shoot ourself as a very clearly worded DON"T DO THIS IF YOU CARE ABOUT SECURITY disclaimer? Rather than playing nanny to all of us foot shooters, or forcing someone to invest in a fork...don't give us a security complex solution...just dump the nonce to our local machine (hell don't even encrypt if its too much work) with a clear disclaimer that WE AGREE TO SELL OUR SOUL TO THE LESS SAFE DEVIL...you can enforce this with a small build option and somebody I am sure will volunteer to keep a compiled version going. 

Its just a lot of work for one of us to go through a codebase we don't know half as well as you to figure out where to dump and reload the none. So please be flexible and help.

foot shooter here

**Comment by eminence** [comment]
As a reminder, you can set the `MOSH_SERVER_NETWORK_TMOUT` environment variable to have a detached mosh-server automatically kill itself after a user-specified time period.  This doesn't solve the feature that's being requested in this issue, but can help with the mosh-server clean-up process (by allowing you to ignore detached mosh-server processes with the knowledge that they will eventually be cleaned up automatically).  This environment variable was added in mosh 1.2.6

**Comment by kentmartin73** [comment]
I really think this is a nifty little bit of software, and, commend the great dev work.  Unfortunately, my main use for it is when I'm travelling and on dicey internet connections strange little corners of the planet, as well as on the VPN into work which may or may not stay up for long periods  Not being able to resume disconnected sessions is what prevents me using MOSH at all really.  It is in my "this'll be a great day to day tool one day, but doesn't fulfil the need for me right now".

I'd too would like to see the _DOYOUHATEYOURSELF = True_ option being able to be set somewhere.

**Comment by eminence** [comment]
To be clear, what this issue is talking about are "detached" mosh-servers where the client has crashed or died (for example, if your laptop ran out of battery and turned off unexpectedly).    

You can always resume a connection (even after months/years), as long as both mosh-server and mosh-client are still running.

**Comment by dgentry** [comment]
And you can certainly resume a session if the first thing you do upon
connecting to a remote system is to start a screen or tmux session and then
when your laptop dies and you have resumed with a new mosh session to the
server, manually kill the old mosh server and reconnect to the screen or
tmux session, it's just not as convenient.  (Problems with screen/tmux
aside.)

At this point, I would settle for an error message that didn't raise my
hopes of getting my mosh session(s) back, and it would be a bonus if it
included the cut/pasteable text "kill <pid> [<pid>. . .]" where the args
are the specific mosh sessions I probably now want to kill.

**Comment by andersk** [comment]
@dgentry See [this comment](https://github.com/mobile-shell/mosh/issues/394#issuecomment-215987982) for one-line aliases that do everything you described automatically.

**Comment by Hello1024** [comment]
Here is a proposed design which I believe eliminates the (valid) security concerns, and opens no additional attack surface.

Session 1 connects as normal.  There is no backdoor to recover the session key or nonce.

Session 2 connects with a "resume" option.  The mosh server process looks for sessions eligible for restoration (for example, by name or by a client timeout).   Upon identification of a suitable server process, it uses the ptrace() syscall to *replace* the key and nonce in memory with the ones it would have used itself, and then quits.   

The client of session 2 can now talk to the server of session 1.   The original client of session 1 can no longer communicate, and any data it sends or receives will not be decrypt-able.

Any other process (malicious or otherwise) could have done this in the server, so this does not open any new security concerns.   The ptrace syscall security is enforced by the kernel, and is allowed by the same user by default.

Anyone care to take a crack at implementation?

**Comment by hinesmr** [comment]
@Hello1024 it's the best step in the right direction that I've heard of so far that doesn't depend on hacks or supplementary software.

So thinking through it, why ptrace instead some other kind of shared file or shared memory via some kind of agreed-upon IPC interaction? 

The only flaw I can think of is defending against two different clients (whom don't trust each other) logging in with the same username (root, for example, although one would hope that doesn't happen very often with best practices), or is that not a fair question to ask?

**Comment by jlsjonas** [comment]
> The only flaw I can think of is defending against two different clients (whom don't trust each other) logging in with the same username
I believe at that point a mosh session should be the least of your concerns

**Comment by RubenKelevra** [comment]
Why are the session keys not temporarily stored on the disk of the client to resume a session for the same client?

This would have zero security implications since the client would just ask for a full screen refresh and use the already build in roaming functionality.

**Comment by RubenKelevra** [comment]
Why are the session keys not temporarily stored on the disk of the client to resume a session for the same client?

This would have zero security implications since the client would just ask for a full screen refresh and use the already build in roaming functionality.

Sure, you have to trust the local harddrive, but this should be encrypted anyway - so that doesn't matter. If the session is closed on the server, you cannot connect anymore with the session data, since they are not valid anymore. So even if you exploit for example a backup location the data isn't usable in any way.

This is pretty important for mobile users (which you're targeting with your application) - they want to be able to recover from an empty battery scenario.

**Comment by Keith-S-Thompson** [comment]
My own issue with this is simply the annoyance of the "You have a detached Mosh session on this server" messages. I don't particularly care about being able to reattach to those sessions. Which is not to say that that ability is unimportant, just that it's not what I'm looking for.

I use mosh to connect from my laptop to my desktop system. If my laptop crashes, it leaves a mosh session running on the desktop. I'm fine with starting a new session every time (I use tmux anyway).

A solution that (a) doesn't leave detached sessions running indefinitely and (b) doesn't show me that message *by default* when I connect would make me happy. A simple config file update that does the same thing would make me nearly as happy.

**Comment by keithw** [comment]
@RubenKelevra Saving the key and nonce to disk would have a lot of security implications. Right now we go through some effort to make sure they won't even be in a core dump. And more practically, if we save them to disk, how can we guarantee they won't be reused more than once? This is catastrophic for the security guarantees of OCB (and most other AE schemes).

@Keith-S-Thompson If you don't want the detached sessions to run indefinitely, you might be interested in setting MOSH_SERVER_NETWORK_TMOUT in the mosh-server's environment. Please see the mosh-server(1) man page for more. (And if you are using tmux already, why not just use mosh to reattach to the old tmux session and detach the existing session...? Then you won't ever have any lingering mosh-server processes because when you reattach and detach the other session, the mosh-server will quit gracefully.)

**Comment by RubenKelevra** [comment]
@keithw well, since they are saved on the same disk as the ssh key which allows full access to the machine anyway, I would think that we would ask the user for a password, if he sets the flag for the ability to reconnect in case the client crashes.

**Comment by msva** [comment]
What do you mean by
> on the same disk as the ssh key which allows full access to the machine 
?
There is only public key stored on the server.
It gives nothing for anyone except private key owner.

**Comment by hilbix** [comment]
There is `tmux`.  There is `reptyr`.

AFAICS with both we can re-attach to a lost `mosh` session.  Hence the only point left seams to be better help from `mosh`.

Here is how to reattach:

Variant 1:  Use `exec tmux new -ADs0`

- Run `mosh example.com -- tmux new -ADs0`
  - Or run `mosh example.com` and then `exec tmux new -ADs0`.  Remember the `exec`
- Local client reboots
- Run `mosh example.com -- tmux new -ADs0`
- This detaches the other `tmux`, and thereby terminates the running `mosh`, too

The only issue here is: Who knows that?  What if you forgot to `tmux new -ADs0`?  Hence the next variant.

Variant 2: You forgot to `tmux new -ADs0`

- Run `mosh example.com` and then `longrunningcommand`
- Local client reboots
- Run `mosh example.com -- tmux new -ADs0`
  - Or run `mosh example.com` and then `exec tmux new -ADs0`.  Remember the `exec`
- OOPS, where is `longrunningcommand`?
- Run `pstree -p | grep mosh`
- This gives you the PID of `longrunningcommand`
- Now run: `reptyr PID`
- If Local Client reboots again, you can use Variant 1 here.

Notes:

- It is crucial to use `reptyr` from within `tmux` sessions only.
  - As you then can easily reattach to tmux again and hence `reptyr`
  - Else you will have problems how to find the client PID of a previous `reptyr` again 
- If `reptyr` is not available then `sudo apt install reptyr`.  It's in Debian.  YMMV depending on Distro.
  - `reptyr` does not always work.  I do not have any clue there.
  - For example `reptyr` does not work with `tmux` clients at my side.  But I would say, this is not a `mosh` issue, more an issue of `reptyr`.
- If you do not use `exec tmux`, you probably still have some no more accessible `mosh` servers running in background.  You can easily find them with `pstree -p | grep mosh`, though
- It becomes more complex if you run multiple `mosh` sessions, of course, or multiple `tmux`.
  - FWIW I use different users for this (usually one `tmux` as user, one `tmux` as `root`, etc.).
  - Note that `sudo` still works with `exec`.

So what's left?

- `mosh` could make it more easy for us to reattach, for example by offering some automation
- Instead of spawning a shell, spawning some "reattach helper" first which tries to autodetect things and do what's usually is wanted.
- If no reattach is needed, just spawn the shell as usual

To be able to write this as a short shell script, here is what I'd like to see from some `list` type command from `mosh`:

- PID of the `mosh` server instance
- How long the last client was seen from this instance (in seconds)
- PTY (master device) for the client
- TTY of the client
- PID of the direct child of the `mosh` server.
  - If it died (but the `tty` is still open) then `-` (if that makes sense)
- The originally forked command name (`bash`, `tmux`, something different)
  - You can get the currently running command from `/proc/PID/exe`

This way you can programmatically create some script which does everything you want.

> I posted this to tell about `reptyr` which I stumbled upon a few minutes ago

**Comment by marc-hb** [comment]
> That message about a detached session made me think it was possible to reattach from mosh somehow. I use screen so it's not a real issue, and screen -dr seemed to kill the old session, but I wish the error was clearer in that I should either connect the same original client again, or kill the session pid. Not sure if you can include that much info in the message...

Too bad this feedback got drown in the number of comments asking for the feature. It's almost 2026 and "You have a **detached** Mosh session on this server" still begs users to waste time searching for a non-existent way to re-attach. I think the problem is mainly with the word "detached": that's the one that makes users look for "(re-)attach". Instead:

- "You have a **orphaned** Mosh session on this server"
- "You have an **unrecoverable** Mosh session on this server"
- "You have a **dead** Mosh session on this server"
- "You have a **stale** Mosh session on this server"
- Etc. - anything that can't be misinterpreted as hopeful.

Single word change; no test required. Pretty please?

**Comment by achernya** [comment]
Detached doesn't mean it's orphan. Imagine the case where you have two laptops, both with mosh sessions to a single server. Unless both laptops are open at the same time, it's expected you'd get this message. None of the suggested wording changes are correct.

**Comment by marc-hb** [comment]
Sincere thanks @achernya for correcting me.

I still think "_detached_ session" is misleading and that we can find better.

"detach"
- is the opposite of "attach" which is not supported.
- is used by both GNU screen and tmux that do support re-attaching.
- sounds like something the user could do. But in mosh, I think it's only a `SERVER_ASSOCIATION_TIMEOUT` (40s?), not the result of any user action.
- sounds like something client and server could agree with each other. But again: only a timeout (and only on the server side?)

I understand this warning is there in case the client died. But the server does not know for sure, it's just a guess. A guess it not easy to communicate but "detached" does not sound like one. Something is either attached or detached, there's a lack of "maybe".

I searched the source and docs and found "**dormant** session": https://mosh.org/#faq

> How can I make the server automatically clean up **dormant** sessions?
> Please see the entries for MOSH_SERVER_NETWORK_TMOUT and MOSH_SERVER_SIGNAL_TMOUT in the mosh-server(1) man page.

Another, IMHO better adjective found in `man mosh-server` is: "**inactive** session"

Neither "dormant" nor "inactive" suggest the (in)ability to re-attach, I find them neutral in that respect. Also, mosh already uses both adjectives, neither is new.


Mandatory naming joke: https://martinfowler.com/bliki/TwoHardThings.html
