### ISSUE TITLE
Mosh doesn't work with socket activated SSH

### ISSUE THREAD

**Issue by niklas88** [mobile-shell/mosh#399]
When running ssh socket activated e.g. by using systemd with "enable sshd.socket" mosh can't establish a connection and times out waiting for an answer.
This seems to be the same problem as reported in 
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686956
but I failed to find an issue with "sslh" mentioned on github

**Comment by bharrisau** [comment]
Sorry for bringing an old issue up. I've been looking into this for CoreOS, the issue is that systemd will default to killing everything when the sshd socket is closed. Which means mosh-server will output the connect line, but be killed before mosh-client can connect to it.

The solution is to change KillMode to process so only the sshd process is closed when the socket is closed.

**Comment by cgull** [comment]
pam_systemd is apparently also relevant: http://comments.gmane.org/gmane.comp.sysutils.systemd.devel/19311
(Still not a bug in mosh.)

**Comment by jamespinkerton** [comment]
Hi. I'm getting the same problem. I tried to add the --bind-server=any and it didn't work.

I ran the following command:
`mosh --bind-server=any --ssh="/usr/bin/ssh -i ~/.ssh/google_compute_engine.pub" james_c_pinkerton@$IP_ADDRESS`

**Comment by reuben** [comment]
For others running into this issue, a way I found for working around this problem without changing the sshd configuration is by using `--server="systemd-run --scope --user mosh-server"`.

**Comment by kecsap** [comment]
My systemd kills screen and mosh sessions associated to ssh, but only on one Ubuntu machine where KDE Neon is installed. In my case, mosh only worked with this option: --server="sudo systemd-run --scope sudo -u USERNAME mosh-server" where USERNAME is my login username and it can execute commands with sudo without password.
