### ISSUE TITLE
 You have a detached Mosh session on this server 

### ISSUE THREAD

**Issue by thomask77** [mobile-shell/mosh#403]
Hi!

I accidentally closed my local mosh window. When I'm making a new connection, mosh displays a friendly "You have a detached Mosh session on this server" message, but doesn't give any hint on _how_ to reconnect.

Even the man-page doesn't help :-/

I thought, reconnecting and handling flaky connections was one of the main features of mosh?

Please add a short help text of how to reconnect. I think it would be best to display a copy/paste'able command right in the "detached session" notification bar.

**Comment by phinze** [comment]
Stopping by to say I too was confused about what to do with stale connections. After reading this thread I decided I could sacrifice my current connection and ran:

```
killall mosh-server
```

That seemed to clean everything up like I wanted. (I run tmux inside of mosh so I wasn't worried about losing any state.)

**Comment by f3xius** [comment]
We can kill all of the mosh-servers except for the last one started. My assumption is the last mosh session started is the one you are currently using.

kill $(ps --no-headers --sort=start_time -C mosh-server -o pid | head -n -1)

**Comment by hickford** [comment]
A warning to others: if you build up too many detached sessions, you won't be able to login by mosh or ssh. Yesterday I had about 20 detached sessions, today I'm locked out my (headless) Raspberry Pi.

```
Could not connect via ssh: Socket error: No more processes

SSH Login failed.

Mosh has exited.
```

Can anyone suggest a solution other than pulling power to reboot?

**Comment by rpwoodbu** [comment]
@hickford 20 sessions isn't nearly enough to cause this problem, even considering that each will take a couple of PIDs at least.

The problem you describe is caused by something chewing up the thousands of available PIDs on the machine. One possibility is a fork bomb. Another is a service that is configured to have too many processes (check Apache, NFS, etc.).

Search the web for "no more processes" for aid here. You may be able to get back in without a hard restart, but it will depend on the root cause and likely will be tricky or impossible.

**Comment by cgull** [comment]
@hickford: I can't reproduce this, on an RPi2 with Raspbian and 25 sessions.

Your problem might be some other kind of resource exhaustion, for example memory, or ptys.

Mosh has some features to enable slightly easier management of detached sessions, see the text on `MOSH_SERVER_NETWORK_TMOUT` and `MOSH_SERVER_SIGNAL_TMOUT` in the `mosh-server` man page.

**Comment by studgeek** [comment]
I came up with the following to close all detached sessions only. It seems cleaner than the alternatives because I don't want to kill my current session, may have more than one detached session, and may have multiple attached sessions. I posted more info on it and also on using `MOSH_SERVER_SIGNAL_TMOUT` at https://stackoverflow.com/a/48082431/255961.

```bash
who | grep -v 'via mosh' | grep -oP '(?<=mosh \[)(\d+)(?=\])' | xargs kill
```

**Comment by ctrlcctrlv** [comment]
@studgeek Wow, it's amazing how close yours is to one I just came up with:

    who|awk '{print $7};'|grep -o '[0-9]\+'|xargs kill

Not sure whose is better ;-)

**Comment by andersk** [comment]
@studgeek @ctrlcctrlv Warning: never run any of these `who | awk | grep | xargs kill` pipelines on multiuser systems. The output of `who` is entirely controlled by those users (which is why `mosh-server` can write its pid there in the first place). Nothing stops them from spoofing arbitrary pids for you to kill.

**Comment by keur** [comment]
@andersk good point. also i think everyone is overthinking this with those crazy awks...

`pgrep -u "$USER" mosh-server | tr ' ' '\n' | grep -v "$PPID" | xargs kill`

Just alias this and run it right when you login and see the message.

**Comment by perguth** [comment]
@keur That line is killing active sessions too... :-/

**Comment by abhi1010** [comment]
> @andersk good point. also i think everyone is overthinking this ...
> 
> `pgrep -u "$USER" mosh-server | tr ' ' '\n' | grep -v "$PPID" | xargs kill`
> 
> Just alias this and run it right when you login (with mosh) and see the message.

Just don't run this from within `tmux`  :)

**Comment by egormanga** [comment]
I'm surprised no one mentioned [`reptyr -T`](https://github.com/nelhage/reptyr) for the purpose of stealing dangling sessions instead of killing them.
