### ISSUE TITLE
Wipe detached sessions

### ISSUE THREAD

**Issue by gsf** [mobile-shell/mosh#426]
Since mosh can't reattach to detached sessions, it should either automatically remove detached sessions or at least provide a --wipe convenience flag to wrap the grepping and killing of processes. See earlier issues around detached sessions: #394, #346, and #403.

**Comment by LwsBtlr** [comment]
A command to clean detached mosh sessions would be very helpful. perhaps with a flag for the number of days since last activity before a session is removed.

After using mosh fairly lightly from only a couple of devices (Blink on iOS and mosh from the command line of a couple of machines) I can easily stack up a dozen detached sessions and removing each one individually is a chore. I am not sure what the exact mechanism for restoring a connection is, but at least in Blink it  seems to start a new session if it's been more than a day since I last connected. Might be an issue with Blink?

**Comment by keithw** [comment]
@LwsBtlr Please see the mosh-server(1) man page -- we now have a timeout that can automatically clean up old sessions (or can clean them up in response to a signal).

**Comment by NightMachinary** [comment]
See 
https://git.zx2c4.com/mosh-cleaner/about/

**Comment by matonga** [comment]
I think this could be handled conveniently by the mosh-client, by taking note of the machine's mac addresses, as I really doubt someone would clone a VM without changing them. Most virtualization tools take care of this automatically. Plus it would also work for physical machines too. The only problem I can see if you hot-swap network cards (is that even possible?) on physical machines, other than that if you shutdown the machine first then you have already closed or killed all relevant mosh-client instances anyway.
