### ISSUE TITLE
iOS server (iPad, iPhone)

### ISSUE THREAD

**Issue by graingert** [mobile-shell/mosh#442]
It would be useful to have a copy of the mosh-server packaged for the cydia store

**Comment by achernya** [comment]
As part of a mosh issues triage, we've concluded that the mosh project has no current plans to work on this issue. To accurately reflect that work on this issue is not planned, we're marking this issue as "closed". We still welcome contributions from community members who want to work on this issue. Please feel free to file pull requests re-opening this issue in the future.
