### ISSUE TITLE
Fast native emacs client

### ISSUE THREAD

**Issue by Intensity** [mobile-shell/mosh#467]
Since an Emacs implementation would be free of a traditional terminal interface, it could potentially be quick and versatile, and this in its own right may make it possible to do even more in Emacs. :)  I'm interested to hear ideas around this.  The emphasis can be on speed, since I believe in order to perform certain operations in a terminal, this still must be encoded locally as a series of escape sequences via curses or termcap, and so it is bound by a legacy interface.  Emacs could be considered one other terminal type, able to jump around and perform an arbitrary function like moving text or jumping to a mark.  A particularly fast implementation could also leverage some C code but can make use of the versatility of Emacs.  A window size change could also be handled elegantly.  This could be integrated with eshell or tramp or other Emacs modes.  And ideally the Emacs client could manage multiple windows or instances itself, consuming some functionality of GNU Screen or tmux.

**Comment by edrex** [comment]
I'd really like to see this happen, since it seems likely to cause fewer program hangs than the SSH transport in TRAMP.

There's a lengthy thread from 2012 working towards an implementation [here](http://comments.gmane.org/gmane.emacs.tramp/8007). Still sifting through to understand how far they got.

**Comment by edrex** [comment]
In [this post](http://comments.gmane.org/gmane.emacs.tramp/8007) the PI from that thread refers to mosh #41 as a prerequisite, so this looks to be blocked on the mosh side.

**Comment by raamdev** [comment]
Putting my vote in for a native Emacs client. I'm in the process of switching everything over to Emacs and was sad to find that mosh did not work inside Emacs.

**Comment by voronoipotato** [comment]
This will also probably help windows support. Emacs works very well within windows.

**Comment by sai-prasanna** [comment]
Anyone working on mosh for tramp?

**Comment by pdblood** [comment]
Would be great to see this happen.

**Comment by gitrj95** [comment]
are there any updates on this?

**Comment by achernya** [comment]
As part of a mosh issues triage, we've concluded that the mosh project has no current plans to work on this issue. To accurately reflect that work on this issue is not planned, we're marking this issue as "closed". We still welcome contributions from community members who want to work on this issue. Please feel free to file pull requests re-opening this issue in the future.

**Comment by elliott-sh** [comment]
+1
