### ISSUE TITLE
Mosh's memory footprint becomes extremely large when pasting large inputs

### ISSUE THREAD

**Issue by tsuna** [mobile-shell/mosh#482]
I have 252KB in the paste buffer.

```
$ pbpaste | wc
    8064   44352  258108
```

When I paste this into a fresh mosh session, I see mosh-client's resident set size balloon to 5GB.

Environment:
- OS X 10.8.5 (Darwin damogran.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64)
- mosh 1.2.4 from Homebrew on the client
- mosh 1.2.4 from mosh-1.2.4-1.fc14.x86_64.rpm on Fedora on the server

**Comment by cgull** [comment]
I just tried reproducing this.  On OS X 10.10 to an RPi2 running Raspbian, pasting the Mac's /etc/services (677KB) with command-V in Terminal, I saw Homebrew's 1.2.4 Mosh client bloat to 3GB of core (and later shrink to 121MB).  When I tried this with my performance code in #531, though, mosh-client stays at 25MB.  I don't know why; I don't think this code should have any positive effect on your problem.  Could you try this code?

**Comment by phmarek** [comment]
Confirmed with the debian package 1.2.4a-1+b2.

**Comment by cgull** [comment]
I've pulled #531.  Can either of you report whether this problem still exists?

**Comment by cgull** [comment]
Still a problem.
From a FreeBSD client running 1.2.5.95rc1 I saw my client bloat to 5+ GB and take about 45s CPU to transmit that same 677KB.  Mosh's timeout message also appeared for most of that time.

**Comment by cgull** [comment]
I had a look at this.  The problem is the prediction code: I saw an individual overlay cell with 27000 predictions piled up on it.  Part of this is that the prediction mode's "insertion" behavior makes a new prediction for each cell right of the cursor each time a new character is input.  Mosh behaves much better when `--predict=none` is used.

It should certainly be possible to make the prediction code aware of bulk pastes (they're visible as large reads on the tty), or make it reset/collapse state when it sees a carriage return, or something.  I haven't come up with the right answer yet though.

**Comment by cgull** [comment]
Some other things are apparent from having tried to fix this:
* The prediction code also does not scale well on CPU usage, I think it's spending all its time in `PredictionEngine::cull()` touching huge lists of predictions/saved bytes.
* But there's really no point in letting prediction run on large amounts of input beyond what a person can type interactively anyway.
* Even with the fix in #885 Mosh is still pretty slow copying pasted bytes from the user...
* ...but that's sort of OK; it probably saves us from generating large Messages that fragment into a zillion UDP packets and don't make it across to the receiver anyway, which is another potential problem with pastes into Mosh.
