### ISSUE TITLE
Client hostname not shown in "who/w" utmp information

### ISSUE THREAD

**Issue by zorinlynx** [mobile-shell/mosh#483]
Normal SSH sessions do a reverse lookup of the client IP so you see a hostname in the server "who" output. Mosh sessions do not.

Yes, this is more of a "cosmetic" issue, but it's often handy to see, at a glance, the hostnames users are moshing in from, particularly on busy servers dedicated to providing UNIX shell access to a community.

Example:

flynnj@vixen:~ 106% who
flynnj   pts/0        2013-12-27 12:46 (backup.cs.fiu.edu)
flynnj   pts/1        2013-12-27 13:08 (sarafina.cs.fiu.edu)
flynnj   pts/2        2013-12-29 10:51 (173.9.162.197 via mosh [10383])

(The first two are normal SSH sessions, the last is a mosh session)

**Comment by achernya** [comment]
mosh unfortunately doesn't know the hostname, as it may not match the IP address resolved. I don't think this cosmetic issue can be easily resolved.

**Comment by cross-cisco** [comment]
Does sshd "know" this information from the client passing it on, or does it just do as one would expect and use DNS to resolve from the address?  If the latter, then there's no reason mosh shouldn't also do this.
I'll not suggest reopening this until I know ssh is doing the same rather than passing on knowledge from the client.

**Comment by achernya** [comment]
ssh is TCP based and does not support IP migration. A single reverse DNS lookup is likely adequate for the ssh case; for mosh it would need to be continuous.

**Comment by cross-cisco** [comment]
Right.  I didn't think about it thoroughly enough at first.  This makes perfect sense.
