### ISSUE TITLE
Optionally alert (once) when the connection works again

### ISSUE THREAD

**Issue by phmarek** [mobile-shell/mosh#495]
When using a bad connection, it would be nice to get notified by mosh-client (eg. via a dbus popup) if the connection was alive again.

I'd imagine using ''Ctrl-^ a'' (for alert) would be easy to remember.

**Comment by achernya** [comment]
As part of a mosh issues triage, we've concluded that the mosh project has no current plans to work on this issue. To accurately reflect that work on this issue is not planned, we're marking this issue as "closed". We still welcome contributions from community members who want to work on this issue. Please feel free to file pull requests re-opening this issue in the future.
