### ISSUE TITLE
Mosh over ssh?

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [mobile-shell/mosh#575]
Hi Mosh team,

I routinely access remote high performance clusters via ssh and often there are restrictions imposed by sys admins in the set of tools that they are willing to install. Is there a possibility of offering some of the features that mosh offers without explicitly having a mosh-server? mosh-clients that interact with ssh-servers underneath would be great. Are there any such plans in the future?

Thanks

**Comment by LuckyHyena** [comment]
@keithw is there a simple way to build statically? im trying to install on some redhat servers. im not experienced with the gnu build tools and haven't been successful trying to get a static flag enabled in the configure or the makefile

**Comment by OmgImAlexis** [comment]
@keithw what about option to have mosh connect and copy the binary over to `/tmp` or whatever tmp dir the user has access to and then run the server?

**Comment by javabrett** [comment]
I looked into building a static binary ... almost got there, but I don't think it is the way to go.  Better to use a normal binary, but knowing that you also need to bundle any missing dependencies with it when setting-up `mosh-server` on the remote.  This can also get around the otherwise need for _root_ access to install dependencies into central locations.

**Comment by achernya** [comment]
Closing in favor #188
