### ISSUE TITLE
semantic versioning?

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#620]
In https://github.com/keithw/mosh/issues/616#issuecomment-109069210, @xtaran suggests using semantic versioning (http://semver.org).  Dependencies on Mosh are not likely to be a big deal because it's an interactive application, but I'm sympathetic to the idea anyway.  By those rules, the next version of Mosh would be 1.3.0, not 1.2.5, since there are significant new features already in Git.  (If Mosh had followed these rules from the beginning, Mosh would already be at a much higher 1.x.x version number.)  How do people feel about this idea?

**Comment by keithw** [comment]
We don't really have a public API, so I guess I don't feel that strongly. I would rather reserve 1.3 for a significant improvement, vs. small additions. E.g. it seems silly go to 1.3 because we added support for changing the escape sequence via an environment variable, even if this is technically "new, backwards compatible functionality."

**Comment by cgull** [comment]
I don't feel that strongly about semantic versioning API, so I'm OK with 
1.2.5

But I will point out that the SSP protocol, and (to a lesser degree) 
terminal emulation, command-line flags and behavior on invocation, *do* 
form an API that other programs can use to invoke or talk to Mosh.  Also 
that since 1.2.4 we have added mouse support (and someday we'll get it 
working!) and non-roaming IPv6.

**Comment by cgull** [comment]
I am feeling more strongly that semantic versioning is a good idea, and I would like to do it for the upcoming release.
