### ISSUE TITLE
avoid failing to connect because locale is not set

### ISSUE THREAD

**Issue by dch** [mobile-shell/mosh#662]
On OSX and other systems without a locale set outside the terminal, mosh fails to connect due to missing locale information.

Why not Do What I Mean and just assume a default locale?

While my handling of the environment variables might not be appropriate, this quick hack may help find a better way forward.

```diff
--- mosh.orig	2015-08-08 00:04:26.000000000 +0200
+++ mosh	2015-08-08 00:04:06.000000000 +0200
@@ -331,11 +331,16 @@
   my @names = qw[LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL];
 
   my @assignments;
-
+  my $default_locale = 'en_US.UTF-8';
+  
   for ( @names ) {
     if ( defined $ENV{ $_ } ) {
       push @assignments, $_ . q{=} . $ENV{ $_ };
     }
+    else
+    {
+      push @assignments, $_ . q{=} . $default_locale;
+    }
   }
 
   return @assignments;

```

**Comment by andersk** [comment]
No, setting the undefined locale variables to `en_US.UTF-8` will break things for users who need some other UTF-8 locale. For example, `LANG=zh_CN.UTF-8` and `LC_ALL=en_US.UTF-8` has a very different meaning from `LANG=zh_CN.UTF-8` and `LC_ALL` undefined.

The right way to make sure that Mosh finds a UTF-8 locale on the server is to set the variables properly on the client, so that the existing codepaths can pass them along.
