### ISSUE TITLE
Strange behavior when I go deeper down the rabbithole

### ISSUE THREAD

**Issue by thomasfrivold** [mobile-shell/mosh#665]
I have a problem with Mosh:
If I "mosh" my Debian server and from there ssh my VPS/webhost I get problems. 
Peculiarily within nano and vim on the VPS, the cursor position loses precision and the active line is sometimes garbled within 5 characters of the active cursor. 

This behavior is replicated every time. The "fix" is that I have to connect to my server with SSH and connect to my VPS with SSH from there, and the issue disappears completely.

**Comment by cgull** [comment]
There's not enough information here to act on.  We can't do anything without knowing at least some of these:

* OSes involved on all three machines
* Versions of Mosh, client and server
* A more precise description of the misbehavior
* Screenshots if possible
* What happens if you type ^L inside nano or vim?  Does that clear the corruption?

**Comment by BrianRossmajer** [comment]
Does it change if you use --predict=never when you connect?

**Comment by andersk** [comment]
This is a shot in the dark due to missing information, but the symptoms sound like they match #539.

**Comment by cgull** [comment]
I've fixed #539.  Please give current Mosh sources a try if you can.

**Comment by cgull** [comment]
We think this is fixed, closing for now-- please reopen if this is still affecting you.
