### ISSUE TITLE
No support for ssh -D option

### ISSUE THREAD

**Issue by SamCyanide** [mobile-shell/mosh#671]
Using the command `mosh user@example.com --ssh="ssh -D 8080 -i ~/Desktop/key.pem"` works fine with regards to the key part, however the '-D' option does not tunnel. Attempts to use this to proxy other applications or your Linux environment do not work.

**Comment by eminence** [comment]
This is expected, since mosh does not support any type of tunneling or port forwarding.

But moreover, mosh only uses ssh to startup the `mosh-server` executable on the remote side.  Once this is done, the ssh connection is terminated.  So in fact with your example, the transient SSH connection will have dynamic port forwarding, but only for the few seconds that the SSH connection is up

**Comment by andersk** [comment]
Correct (#261, #337).
