### ISSUE TITLE
IPV6 MTU issues

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#688]
For the third or fourth time recently, we're discussing what seems to be an IPv6 MTU issue on #mosh, where the client loses contact with the server after a large screen update causes the server to generate maximum-sized packets.  Mosh needs to do better with IPv6, by either being smarter about MTU when things aren't going well, or by simply limiting itself to IPv6's 1280-byte minimum.

**Comment by cgull** [comment]
And indeed, this one was an MTU issue as well.

**Comment by keithw** [comment]
Yeah, I think the problem is that IPv6 really doesn't have in-network fragmentation. Given our experience with this, I think our options are:

(1) Develop our own in-band Path MTU discovery approach that takes "absence of an authentic acknowledgment" as a clue that the Path MTU may need to be lowered. (Depending on ICMP too-big messages is just not workable.)

(2) Go down to 1280 bytes.

**Comment by andersk** [comment]
I don’t know if this is part of the problem, but does [`static const int HEADER_LEN = 66`](https://github.com/mobile-shell/mosh/blob/mosh-1.2.5/src/network/transportfragment.h#L47) need to be recomputed for IPv6?

**Comment by cgull** [comment]
Yes, yes it did.  It was not obvious what the desired MTU was or why it was chosen, so I reworked things to make the chosen MTUs and calculations clear.

I picked an IPv4 MTU of 1380 based on mobile tethering tests I did and packet captures I have available-- if anyone else has an opinion here, toss your number into the ring.
