### ISSUE TITLE
Need to distinguish multiple logins that have the same uid

### ISSUE THREAD

**Issue by fortran77** [mobile-shell/mosh#695]
Suppose a server's password file contains:

    root:x:0:0:root:/root:/bin/bash
    bobroot:x:0:0:bobroot:/home/bobroot:/bin/tcsh

Here, "bobroot" is another user with uid=0 and gid=0. This allows having a separate environment for this user—custom home directory, dot files, and login shell—but still allowing full root access.

Ordinarily, when I use ssh to log into the server (running CentOS 5.11) as user bobroot, I see the bobroot environment, and "who" and "last" show logins from bobroot, not root. But if I log into the same server as user bobroot from the mosh app on a Chromebox, I find myself logged in as "root", not as "bobroot". I can of course then do 'su -l bobroot'. It would be nice to be able skip this step and directly log in as bobroot using mosh.

If needed, mosh-server should be able to consult the environment variable LOGNAME to let it pick the correct match from the list of answers from getpwnam(getuid()).

**Comment by cgull** [comment]
Well, there's two parts to this:

* utmp logging.  We're at the mercy of utempter here.  There's no good fix for this, other than going back to a Unix that allows world-writable /var/log/utmp.  sshd can get this right because it runs as root and can write utmp itself.  Interestingly, the FreeBSD utempter implementation *does* correctly identify a shared-UID user.

* User environment.  If `HOME` or `SHELL` are unset, mosh uses `getpwuid(geteuid())` to get the relevant info-- which of course will be `root`'s info in your scenario.  But those two variables should normally be set for an interactive login, and you shouldn't see this problem.

What version of mosh are you using on the server?  Are you running mosh in the standard way with the mosh script, or have you implemented some other method for starting a mosh session?

**Comment by fortran77** [comment]
I am using the latest-available mosh installed from the EPEL repository onto a machine running CentOS 5.11. The rpm is mosh-1.2.4-1.el5 and the documentation resides in `/usr/share/doc/mosh-1.2.4` so it must be revision 1.2.4.

(Hoping to find a version number embedded in the binary, I typed "`mosh-server --help`" and "`mosh-server -v`" and got only a "Bad IP address" error. Also tried "`ident`" and "`strings -a`" with no luck.)

I am invoking the client from the Chrome app that was installed from the Chrome Web Store. I click on the icon to make the app run, then I fill in the username and hostname, leaving everything else as default (i.e.: address family is IPv4, SSH port is 22, remote command is blank, Mosh server command is blank), and then I click on the Connect button. And it logs me in as root instead of bobroot.

When I use ssh (not mosh), all the usual environment variables, including HOME, USER, and LOGNAME, are found to be correctly set. This is so even in a non-interactive command like "`ssh bobroot@server 'echo $USER'`".

**Comment by cgull** [comment]
Right, mosh-1.2.4.  I suspected this was the case...

Upgrade to mosh-1.2.5 on your server.  That version of mosh-server will respect `$HOME` as set up by the ssh connection, and your login environment will be as you expect.

**Comment by fortran77** [comment]
Thanks, your prompt response much appreciated. (I might just wait for the EPEL repository to catch up.)
