### ISSUE TITLE
Return code from mosh to use in scripts

### ISSUE THREAD

**Issue by uzytkownik** [mobile-shell/mosh#720]
I'm using mosh to run long running computations, such as builds, on remote system in road warrior setup. That works quite well except that I cannot return any code from them to, for example, break a script. Could mosh forward error code from script to caller?

**Comment by cgull** [comment]
Mosh is fundamentally an interactive terminal, like `telnet`, rather than a remote shell for commands like, well, `rsh`.  The exitcode it returns reflects the success or failure of the terminal session, rather than the remote commands run in that session.

I think it wouldn't be too hard to add support for passing exitcodes through from the server, but it would have to be an option, for best compatibility.  What do we do if a new client requests this from an old server, though?  We could always return a fixed exitcode, or revert to the old behavior, but any of these behaviors will be surprising in some situation.

Implementing a side channel that can report either a remote exitcode or its unavailability might be better, something like `--remote-exitcode-on-fd=4`?

**Comment by timofonic** [comment]
@cgull 

Is rsh still used? It isn't uses SSH!

That would make it a lot more interesting. Having rsh capabilities would be interesting too :D

**Comment by cgull** [comment]
I was just using `rsh` as an example.  `rsh` isn't used much any more, but `ssh` was intended to be compatible.  `ssh` works in a very similar way.
Mosh isn't really intended or designed for programmatic execution of remote commands.  It's designed for interactive use by a live user.

**Comment by cgull** [comment]
Another problem with having Mosh return an exit code when a session ends is that the client doesn't always know when the session ends on the server, and wouldn't always get an exit code.  If the client loses connectivity while the server exits, the client misses its chance to see any exit code that would be sent by the server, and doesn't even know the session has ended.  So any solution for this cannot be reliable, at least not without additional changes to the server to make it wait for the client to reappear.

**Comment by achernya** [comment]
I don't think mosh should support this. Simply tunneling the return code isn't very useful, as you'd not see the last command output as the screen is set back to its normal mode after mosh-client exists. I think this is a great use case for screen or tmux, possibly accessed by mosh or ssh.
