### ISSUE TITLE
PS1 display problem

### ISSUE THREAD

**Issue by rememberli** [mobile-shell/mosh#726]
Hello, I have my PS1 as below 
```
PS1='`a=$?;if [ $a -ne 0 ]; then a="  "$a; echo -ne "\[\e[s\e[1A\e[$((COLUMNS-2))G\e[31m\e[1;41m${a:(-3)}\e[u\]\[\e[0m\e[7m\e[2m\]";fi`${debian_chroot:+($debian_chroot)}\[\e[1;33m\]\u\[\e[1;31m\]@\[\e[1;35m\]\h\[\e[1;32m\][\t]\[\e[1;31m\]:\[\e[1;36m\]\w\[\e[1;34m\]\$\[\e[0;39m\]'
```
When I type wrong command via SSH connection,it works well, displaying like this:
![2](https://cloud.githubusercontent.com/assets/9067053/13650767/3afd647a-e67f-11e5-9e9a-5fa11b2f6ebb.jpg)
Then  I got wrong display(user name broken) with mosh connection:
![11](https://cloud.githubusercontent.com/assets/9067053/13651176/1e282b8a-e681-11e5-8a08-52a00c874e04.jpg)

Could you pls help check where the problem is? Thank you.

**Comment by cgull** [comment]
Wow, that's a complicated `PS1`, and it exposes some fairly subtle behavior.

Anyway, the problem is twofold:

- It uses `ESC` `[` `s` and  `ESC` `[` `u` to save/restore the cursor position, in the code that displays non-zero exitcodes.  These escape sequences originate from the ancient and rather-unique terminal emulation in MS-DOS ANSI.SYS, and Mosh doesn't support them.  On most terminal emulators, this would be fairly harmless, since these escape sequence only have a very small effect here, but...
- Unlike most other terminal (emulations), Mosh doesn't quite completely ignore unknown/unsupported escape sequences.  When it receives the `ESC` `[` `u`, it repositions the cursor as if a printing character had brought it to its current location.  But at this point, a character (the last digit of the exitcode) has been printed at the last column in the line, which invokes a special behavior of VT-100 compatible terminals where the cursor is displayed at the last column of the screen (before the printed character, not after) and not wrapped to the next row.  In Mosh, the unknown escape sequence erases the bit of state for this special behavior, and since it's unknown, it doesn't reposition the cursor, of course.  So Mosh now believes the cursor is before the last column on the original row, and the unconditionally-printed part of your `PS1` is displayed starting from there.
I believe that's a bug/incompatibility in Mosh, but I haven't gotten around to convincing @keithw of this; it's a pretty minor thing.

The fix/workaround is pretty simple, though:  either use the widely supported DEC VT100 sequences for saving/restoring the cursor (`ESC` `7` and `ESC` `8`), or better yet, eliminate them entirely.  You don't need to restore the cursor back to exactly where it was-- all you need to do is print the exitcode at the end of the line, go to a new line, and print the normal prompt there.  You can insert `\r\n` at the appropriate point for that.  What I come up with is:

```shell
PS1='`a=$?;if [ $a -ne 0 ]; then a="  "$a; echo -ne "\[\e[1A\e[$((COLUMNS-2))G\e[31m\e[1;41m${a:(-3)}\]\[\e[0m\e[7m\e[2m\r\n\]";fi`${debian_chroot:+($debian_chroot)}\[\e[1;33m\]\u\[\e[1;31m\]@\[\e[1;35m\]\h\[\e[1;32m\][\t]\[\e[1;31m\]:\[\e[1;36m\]\w\[\e[1;34m\]\$\[\e[0;39m\]
```
(perhaps the `\r\n` should be outside the `\[`...`\]` pair, I am not sure about this usage-- someone more wizardly with `PS1` can answer that.)

**Comment by rememberli** [comment]
Ah, thank you , now it works well with git branch:
```
PS1='`a=$?;if [ $a -ne 0 ]; then a="  "$a; echo -ne "\[\e[1A\e[$((COLUMNS-2))G\e[32m\e[1;41m${a:(-3)}\]\[\e[0m\e[7m\e[2m\r\n\]";fi`${debian_chroot:+($debian_chroot)}\[\e[1;33m\]\u\[\e[1;31m\]@\[\e[1;35m\]\h\[\e[1;32m\][\t]\[\e[1;31m\]:\[\e[1;36m\]<\w>\[\e[1;35m\]$(git rev-parse --abbrev-ref HEAD 2> /dev/null || echo "")\[\e[1;34m\]\$\[\e[0;39m\]'
```
