### ISSUE TITLE
iftop line drawing doesn't work unless inside tmux

### ISSUE THREAD

**Issue by damageboy** [mobile-shell/mosh#775]
Hi,
I'm using gnome terminal to connect to a remote mosh server.

When I connect directly with mosh and run iftop, my terminal looks like this:
![image](https://cloud.githubusercontent.com/assets/125730/16711951/164f454e-467e-11e6-8b66-4ed605dd2c8c.png)

The output of `locale` is:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

When I run the same application under tmux, I get:
![image](https://cloud.githubusercontent.com/assets/125730/16711954/2c40b702-467e-11e6-88db-037e1092e83a.png)

The output of `locale` under tmux is:
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

I suspect that what is happening is that iftop outputs "normal" ACS charchters, and not using the unicode range when run with UTF-8, (unlike midnight commander, for example, which works well)
And when run under tmux, this is somehow magically translated by tmux to the UTF-8 space?

Does this make sense? Is there anything I can do a a user, except than to fix upstream packages that doesn't use the unicode chars for ACS when running in UTF-8?

**Comment by keithw** [comment]
I think your diagnosis is probably correct. mosh-server sets the `NCURSES_NO_UTF8_ACS` environment variable, which makes curses programs use UTF-8 instead of ISO 2022 for line-drawing. Unfortunately iftop doesn't seem to honor this.

You can fix the problem by running iftop inside "luit", e.g.:

`sudo LANG=C luit iftop`

luit is intended to translate from ISO 2022 to UTF-8. (http://invisible-island.net/luit/)

Or you can run iftop inside screen or tmux, which will do the same thing (albeit in somewhat more heavyweight fashion).

**Comment by damageboy** [comment]
Thanks for dropping the knowledge both on `NCURSES_NO_UTF8_ACS` and luit
I'm writing an NCURSES application right now, so thanks for the enlightenment

**Comment by peterwillcn** [comment]
TERM=xterm iftop
