### ISSUE TITLE
Mosh 1.2.6 unable to find Amazon EC2 pem file

### ISSUE THREAD

**Issue by istinspring** [mobile-shell/mosh#797]
OSX 10.11.6 (15G31)

```bash
mosh --ssh="ssh -i ~/.ssh/myamazonfile.pem" ubuntu@server
Warning: Identity file ~/.ssh/myamazonfile.pem not accessible: No such file or directory.
Permission denied (publickey).
```

while mosh 1.2.5 

```bash
mosh --ssh="ssh -i ~/.ssh/myamazonfile.pem" ubuntu@server
```

connect without any problems.

permission on `.pem` file is 400 with my current user as owner

**Comment by glensc** [comment]
looks like tilde `~` is not expanded, try `$HOME` or absolute path

**Comment by andersk** [comment]
When you type `ssh -i ~/.ssh/myamazonfile.pem`, your local shell expands `~` to your home directory. It does not do so inside quoted strings.

It turns out that OpenSSH 7.2 [expands this `~` anyway](https://bugzilla.mindrot.org/show_bug.cgi?id=2481), even when the shell doesn’t. So you can resolve this either by upgrading to OpenSSH 7.2, or by passing the full path to your home directory, or by moving the option into your `~/.ssh/config` file so that the `--ssh` option is no longer necessary:

```
Host server
    IdentityFile ~/.ssh/myamazonfile.pem
```

**Comment by istinspring** [comment]
@andersk but why it's different for mosh v1.2.5 and v1.2.6?

**Comment by andersk** [comment]
@istinspring Probably because of #664.

**Comment by istinspring** [comment]
ah got it, thank you!
