### ISSUE TITLE
Different fonts cause wrong cursor position

### ISSUE THREAD

**Issue by bitsandbytes** [mobile-shell/mosh#848]
I'm using Mosh on Windows 10, Chrome, v0.3.0.258 and Mosh v1.2.6 on Centos 6.5.

I tried changing the font-family to various proportional font-families but when I do that the cursor will be placed further to the right than it should be, like changing:
"DejaVu Sans Mono", "Everson Mono", FreeMono, "Menlo", "Terminal", monospace
to 
"Tahoma",  "DejaVu Sans Mono", "Everson Mono", FreeMono, "Menlo", "Terminal", monospace
And find that cursor is always at least 3 places off to the right, usually more than 3 spaces. Happens at the command-line, in vi, etc.

My questions are: 
- Should I be able to use proportional fonts, do I have to ensure some sort of consistency in available fonts between client and server?
- The only other monospace font that seemed to be recognized was Courier New. Is there any way of knowing which fonts are available to the client?

Thanks! I've only been trying mosh out a day but it's so blazing fast on my AWS VM's that I love it.

**Comment by cgull** [comment]
This is more properly a question asked on the [Mosh for Chrome project page](https://github.com/rpwoodbu/mosh-chrome) since you're using its built-in font selection and terminal emulation, but in general proportional fonts and full-screen console apps (including Mosh, even when Mosh is displaying the output of command-line apps on the remote end) do not mix well at all, because the cursor positioning and screen formatting those apps do expects all characters to line up in fixed-width cells.  Am I understanding your problem correctly?

**Comment by bitsandbytes** [comment]
Yes you understood it correctly, and it's obvious once you describe it that way.

I also wanted to know how I can determine which monospaced fonts are available to mosh. I can ask this on the Mosh for Chrome page. Thanks for your speedy reply! Mosh has made my connectivity issues "go away".
