### ISSUE TITLE
Mysterious mosh-server crashes

### ISSUE THREAD

**Issue by cgutteridge** [mobile-shell/mosh#897]
For the past couple of weeks my mosh-server processes have been crashing and it's really frustrating. I've been using 1.2 client on OSX to 1.1 server on linux (RHEL5.11), but I've upgraded both client and server and am still having the same problem.

I've once managed to capture a "strace" of a mosh-server as it died, but I don't have the chops to debug why it died. I can see that it was trying to write an error to STDERR but I can't work out an easy way to capture that.

Here's the strace log of it dying: [moshsigabrt.txt](https://github.com/mobile-shell/mosh/files/1088270/moshsigabrt.txt)

I've loved using mosh for years, and this is making it unusable! I'm happy to run tests to try to debug further.

**Comment by keithw** [comment]
What are the exact versions of mosh-client and mosh-server that produced this failure?

Can you run the client and server separately (see the instructions on mosh.org) and run the server with `mosh-server new -v` to get debugging output, and capture its output before the crash?

**Comment by cgull** [comment]
Also, both your client and server are rather old, and it's possible the bug is already fixed in a newer version. I'm traveling now and can't find the details but I think there might be newer RPMs available somewhere.  As for debugging you can try `strace -s 250` to get a more complete capture of the error message.

**Comment by cgutteridge** [comment]
Hi. We managed to resolve this. The VM was running NTP but the clock on the underlying computer running the VM was wrong. VMWare tools and NTP were fighting over the VMs clock time making it change in strange ways. Fixing this has fixed all my MOSH issues, so I'm closing the issue. I suspect this was not a bug but correct behaviour, but it might be useful to make it easier for people to see why they server has decided to quit without fiddling with making a connection manually. eg. a log file mosh servers write into by default (or based on a config file?)

**Comment by cgutteridge** [comment]
Hi. We managed to resolve this. The VM was running NTP but the clock on the underlying computer running the VM was wrong. VMWare tools and NTP were fighting over the VMs clock time making it change in strange ways. Fixing this has fixed all my MOSH issues, so I'm closing the issue. I suspect this was not a bug but correct behaviour, but it might be useful to make it easier for people to see why they server has decided to quit without fiddling with making a connection manually. eg. a log file mosh servers write into by default (or based on a config file?)

**Comment by cgull** [comment]
I don't think it's correct behavior, and I think it's actually a minor security issue, because abusing the host clock could be a route to a DoS on existing mosh connect.  (It's minor because on many systems, manipulating the clock requires elevated privileges anyway.)

Did you ever get a trace that captured the text of the error message?
