### ISSUE TITLE
configure: error: OpenSSL crypto library not found

### ISSUE THREAD

**Issue by rkaplan** [mobile-shell/mosh#913]
Due to system constraints, my OpenSSL is installed in a non-standard location: /vision/u/rjkaplan/ssl. I have tried passing this location to mosh's ./configure in a variety of ways, all of them failing. Here is an invocation I think should work, but doesn't:

`./configure --prefix=/vision/u/rjkaplan/local CRYPTO_CPPFLAGS=/vision/u/rjkaplan/ssl/include CRYPTO_LDFLAGS=/vision/u/rjkaplan/ssl/lib`

The last few lines of output are:
...
`checking pkg-config is at least version 0.9.0... yes
checking for TINFO... yes
checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
checking for CRYPTO... no
checking openssl/aes.h usability... no
checking openssl/aes.h presence... no
checking for openssl/aes.h... no
configure: error: OpenSSL crypto library not found`

How can I tell mosh where my openssl is installed?

**Comment by keithw** [comment]
Hello,

The most robust mechanism is to set the PKG_CONFIG_PATH environment variable to the directory where you have installed the `openssl.pc` file.

The other variables take flags to the compiler -- e.g. you'll probably need a `-I` before the include path in CRYPTO_CPPFLAGS, and a `-L` before the library search path in CRYPTO_LDFLAGS as well as a `-lcrypto` to make it actually link with libcrypto.

**Comment by cgull** [comment]
Your configure invocation isn't quite right.  An example that does work on FreeBSD:
`./configure --enable-examples CRYPTO_LIBS='-lcrypto' CRYPTO_CFLAGS='-I/usr/foo'`
(I used `-l/usr/foo` because FreeBSD needs no special compile flags, but I wanted to put something there to verify that the compile commands used it)
Also, if the Nettle crypto library is installed on your system, you can select it with `--with-crypto-library=nettle`.
