### ISSUE TITLE
Enter doesn't work when saving in nano over a mosh connection

### ISSUE THREAD

**Issue by philhagger** [mobile-shell/mosh#915]
I am connecting to my Ubuntu server 17.04 over mosh using Termius on my iPad. Everything seems to work fine but when I edit a file using nano, I press ctrl-x to close and save, press s then enter and nothing happens. It appears that enter is not registered as a press.

Obviously the enter key is working everywhere else.

**Comment by cgull** [comment]
Please note, Termius is a separate implementation of Mosh's functionality.

I've reproduced this bug, the problem is that the Return key sends ^J, not ^M as it should.  You can work around this by manually typing ^M when this problem occurs.  Would you please report this bug to the Termius developers?
