### ISSUE TITLE
ctrl-^ doesn't work on norwegian keyboards on win7

### ISSUE THREAD

**Issue by divinity76** [mobile-shell/mosh#952]
as the title says, ctrl+^ does not work on my win7 x64 ultimate SP1 with a norwegian keyboard and norwegian keyboard layout.

this is especially annoying because, additionally, mosh doesn't understand "reboot" apparently, and thus i have to terminate the shell every time i reboot a system from mosh

using cygwin and the default cygwin shell, 
```
$ mosh --version
mosh 1.3.2 [build mosh 1.3.2]
(...)
$ uname -a
CYGWIN_NT-6.1 hans-lp17 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64 Cygwin
```
- both of which are fully updated, latest released versions as of writing.

**Comment by eminence** [comment]
You can set your own escape key by setting the `MOSH_ESCAPE_KEY` environment variable on the client.  This is documented in the mosh(1) man page.  Does this work for you?

**Comment by divinity76** [comment]
@eminence if you mean like
```
export MOSH_ESCAPE_KEY=a
mosh foo@ip
a
```
then no, not even that works. if that's not what you meant, please explain. also, i updated the original post with version info.

**Comment by eminence** [comment]
What did you intend to set?  `MOSH_ESCAPE_KEY=a` will set it the escape key to the letter `a` (ASCII code 0x61).   Since this is a printable character, you must prefix it with a new line, so press <kbd>enter</kbd> and then press <kbd>a</kbd>.

If you wanted it to be <kbd>ctrl-a</kbd> (aka `^A`) then you need to set `MOSH_ESCAPE_KEY` to ASCII code 0x01.  In most linux shells, the way to enter a literal 0x01 character is to press <kbd>ctrl-v</kbd> followed by <kbd>ctrl-a</kdb>

**Comment by divinity76** [comment]
i intended to set it to `a` because that should be really easy to test. and it was.

however, idk what changed, but **i can no longer reproduce the problem**, both a and ctrl+^ (no MOSH_ESCAPE_KEY variable defined) suddenly works fine now.  in addition, mosh suddenly understands the word `reboot` apparently (which it didn't yesterday, i'm so confused..), anyway, assuming the bugreport is invalid and closing..
