### ISSUE TITLE
mosh Somehost and ssh Somehost come up with different SSH connection parameters

### ISSUE THREAD

**Issue by poige** [mobile-shell/mosh#958]
I've tried to build-in some logic with ssh's Match and Host and during debugging found out _Subj_.

How come? From mosh's man page I concluded it should use `ssh` in a pretty straight way, w/o adjustment to its options. Isn't it true?

**Comment by cgull** [comment]
Mosh should usually run `ssh` similarly to a standalone interactive invocation.  The major exception is that the configuration option `ProxyCommand` will be ignored, because Mosh uses its own connection proxy by default.

Can you be more specific about the problems you're having?  What `ssh` config options are not working for you?  What output/difference do you see when running Mosh?

**Comment by poige** [comment]
> because Mosh uses its own connection proxy by default.

It seems it's clear now why I observe this behaviour
