### ISSUE TITLE
Mosh-client problem 

### ISSUE THREAD

**Issue by scotty1373** [mobile-shell/mosh#962]
Today when i changed my mac language to English(U.S.) , I find out that mosh-client can't recognize the encoding. the error report as follow.

The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to 192.168.31.218 closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

Mosh can be used normally before i changed my mac language. I think the result which cause the issue is the system coding format, actually i still have no ideal to solve this problem.

**Comment by tzing** [comment]
Hi, I've encounter the same issue as you.
Just solved it by set `LC_ALL` to `en_US.UTF-8`

**Comment by asbestomolesto** [comment]
I wonder why mosh-server can't simply start and run without this locale madness. I mean, what's the problem? Why a simple locale setting is preventing mosh-server from starting? 
Why a server for a remote connection must care if I am able to see a particular character or not? 
I really can't understand. 
I had this same problem some days ago and I spent a lot of time debugging it just to discover that my mosh-server wasn't starting because of some locale missing. 
I can't get around it. Is there any rational explanation for this?

**Comment by eminence** [comment]
There's an entry in [the FAQ](https://mosh.org/#faq) about this.

This issue is now 5 years old, and there's a lot of hints in the issue tracker about how to set a UTF-8 locale on various types of machines, so I don't think there's any value keeping this issue open.
