### ISSUE TITLE
up/down arrow keys stop working after reconnect to dtach process

### ISSUE THREAD

**Issue by simonmichael** [mobile-shell/mosh#980]
I have mosh 1.3.2 on client (mac) and server (ubuntu), and dtach 0.9 on the server. To reproduce:
```
mosh -n -- myserver.com dtach -A .dtach htop  # up/down keys work
C-\                                                                # disconnect
mosh -n -- myserver.com dtach -A .dtach htop  # reconnect; up/down keys no longer work
```
This does not happen with ssh:
```
ssh -t myserver.com dtach -A .dtach htop
C-\
ssh -t myserver.com dtach -A .dtach htop
```
or with a different program on the server, like vi, or with a different terminal app on the client (tested in iterm2 and Terminal.app).

**Comment by andersk** [comment]
I can reproduce this with Ubuntu + gnome-terminal on the client and server. However, this is an issue with dtach, not Mosh.

Like many applications, htop puts the terminal into a different mode on startup and restores it on exit. However, dtach (as admitted in its README) does not have a terminal emulation layer, so it doesn’t understand that this mode needs to be saved and restored.

This appears to work out okay if you run dtach twice in a row on the same terminal. Since ssh also doesn’t have a terminal emulation layer (it doesn’t need one, since it doesn’t try to support detach and reattach), this also works if you run it twice in a row over ssh. But you can see that there are problems if you run vi between the dtach commands:

```
ssh -t myserver.com dtach -A .dtach htop
C-\
vi
:q
ssh -t myserver.com dtach -A .dtach htop
```

or if you change to a different terminal window between the dtach commands.

**Comment by simonmichael** [comment]
Thanks for the info! 

I didn't quite understand why this works with ssh but not mosh.
