### ISSUE TITLE
Document choice of aes-128 over aes-256

### ISSUE THREAD

**Issue by kpcyrd** [mobile-shell/mosh#993]
hey!

A friend recently raised a concern about the choice of aes-128 (but was too lazy to post to the issue tracker :P), so I would like to raise this as a documentation request.

Is there a particular reason **for** aes-128, or is there a particular reason **against** aes-256?

aes-128 should be reasonably secure but I think documenting this could be a good idea, if there was a reason at all.

Thanks you!

**Comment by keithw** [comment]
I think the story is basically:

- AES-128 is more than an adequate key length for a session key.

- The OCB FAQ recommends AES-128. (http://web.cs.ucdavis.edu/~rogaway/ocb/ocb-faq.htm#what-blockcipher)

- AES-128 is a bit nicer and is not subject to the related-key attacks that afflict AES-192 and AES-256. (Schneier: "the key schedule for 256-bit version is pretty lousy -- something we pointed out in our 2000 paper -- but doesn't extend to AES with a 128-bit key." https://www.schneier.com/blog/archives/2009/07/another_new_aes.html)

- If you are concerned with security, this is probably not the right thing to be worried about. Over the lifetime of Mosh, systems like the TLS implementations and OpenSSH have had a whole bunch of security holes (some of them related to cipher agility or nonobvious combinations of options). Mosh has had zero major security vulnerabilities ever. The reason our track record is so good is because we focused on what turned out to be the right things -- having a single well-understood mode that was sane, and then not fiddling with it.

**Comment by kpcyrd** [comment]
Awesome, thanks for your reply! Any chance we can get that into the documentation somehow?

**Comment by keithw** [comment]
I think we're open to adding it to the FAQ on the mosh.org website! Do you want to draft a pull request to add a FAQ entry to the https://github.com/mobile-shell/moshweb repo, and we can edit and apply? I do want to continue to keep our security claims modest, both because it's the right thing to do and because inevitably some day we will have a security hole and I don't want us to look silly.

**Comment by eminence** [comment]
Since the original question was answered, I'm going to close this.  But we'll still happily take a PR on the moshweb repo to add this to the FAQ
