### ISSUE TITLE
Crypto exception: Packet failed integrity check.

### ISSUE THREAD

**Issue by tom-doerr** [mobile-shell/mosh#998]
When I run 
`mosh --ssh='ssh -p 39836' -p 2198 abcd.airdns.org`
I get the following output:

`
Failed binding to 10.13.216.16:2198
Error binding to IP 10.13.216.16: bind: Address already in use
Failed binding to 0.0.0.0:2198
Error binding to any interface: bind: Address already in use
Network exception: bind: Address already in use
Connection to abcd.airdns.org closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
`

I started the server myself with
`mosh-server new -vp 60001`, 
but when connecting from the client, the server shows the  following output:
`Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
Crypto exception: Packet failed integrity check.
No connection within 60 seconds.

[mosh-server is exiting.] `

Any idea what the issue could be?  Apparently there's no issue with the port numbers and the firewall, since the `Crypto exceptions` only show up when the client is trying to connect.

**Comment by andersk** [comment]
In normal usage, you need not, and should not, launch `mosh-server` yourself. The `mosh` script expects to use `ssh` to launch its own instance of `mosh-server`; each `mosh-server` instance services exactly one Mosh session (so if no Mosh session is active, no `mosh-server` is running). The `mosh` script cannot communicate with any `mosh-server` other than its own because they share a cryptographic secret unique to that one session.

Try stopping all `mosh-server` processes on the remote machine, and then running the `mosh` script as before. If there’s some other problem that led you to conclude that this wouldn’t work, let’s diagnose it from there.

I’m not sure what the deal is with 2198 not matching 60001, or how you got as far as sending packets to a manually launched `mosh-server`—are you trying to forward traffic from one port number to the other? If you want to use the `mosh` script, the internal and external server port numbers will need to match.

**Comment by tom-doerr** [comment]
Thanks for your quick reply!
Yes, I was trying to forward 2198 to 60001. Using matching port numbers solved the issue for me. 
Thanks!
